(function(){var g={};
(function(window){var k,aa=this;function n(a,b){var c=a.split("."),d=aa;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)c.length||void 0===b?d[e]?d=d[e]:d=d[e]={}:d[e]=b}function p(a,b){function c(){}c.prototype=b.prototype;a.Wb=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Tb=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}};function ba(){return Date.now()+ca}var ca=0;function da(a){return Object.keys(a).map(function(b){return a[b]})}function ea(a,b){var c=fa(a,b,"number");if(null==c)return null;if(isNaN(c)||c==Number.NEGATIVE_INFINITY||c==Number.POSITIVE_INFINITY)throw new RangeError("'"+b+"' must be finite.");if(0>c)throw new RangeError("'"+b+"' must be >= 0");return c}function fa(a,b,c){a=a[b];if(null==a)return null;if(typeof a!=c)throw new TypeError("'"+b+"' must be a "+c+".");return a}
function ga(a,b,c){a=a[b];if(null==a)return null;if(!(a instanceof c))throw new TypeError("'"+b+"' must be an instance of "+c.name+".");return a};function v(a,b){return b.bind(a)};function ha(a){this.b=a;this.a=new ia(a);ja||(ja=[new Uint8Array([255]),new Uint8Array([127,255]),new Uint8Array([63,255,255]),new Uint8Array([31,255,255,255]),new Uint8Array([15,255,255,255,255]),new Uint8Array([7,255,255,255,255,255]),new Uint8Array([3,255,255,255,255,255,255]),new Uint8Array([1,255,255,255,255,255,255,255])])}var ja;
function y(a){var b;b=ka(a);if(7<b.length)throw new RangeError("EbmlParser: EBML ID must be at most 7 bytes.");for(var c=0,d=0;d<b.length;d++)c=256*c+b[d];b=c;c=ka(a);a:{for(d=0;d<ja.length;d++)if(la(c,ja[d])){d=!0;break a}d=!1}if(d)throw new RangeError("EbmlParser: Element cannot contain dynamically sized data.");if(8==c.length&&c[1]&224)throw new RangeError("EbmlParser: Variable sized integer value must be at most 53 bits.");for(var d=c[0]&(1<<8-c.length)-1,e=1;e<c.length;e++)d=256*d+c[e];c=d;c=
a.a.a+c<=a.b.byteLength?c:a.b.byteLength-a.a.a;d=new DataView(a.b.buffer,a.b.byteOffset+a.a.a,c);ma(a.a,c);return new na(b,d)}function ka(a){var b=oa(a.a),c;for(c=1;8>=c&&!(b&1<<8-c);c++);if(8<c)throw new RangeError("EbmlParser: Variable sized integer must fit within 8 bytes.");var d=new Uint8Array(c);d[0]=b;for(b=1;b<c;b++)d[b]=oa(a.a);return d}function na(a,b){this.id=a;this.a=b}
function pa(a){if(8<a.a.byteLength)throw new RangeError("EbmlElement: Unsigned integer has too many bytes.");if(8==a.a.byteLength&&a.a.getUint8(0)&224)throw new RangeError("EbmlParser: Unsigned integer must be at most 53 bits.");for(var b=0,c=0;c<a.a.byteLength;c++)var d=a.a.getUint8(c),b=256*b+d;return b};function qa(a,b){for(var c={},d=0;d<a.length;++d){var e=b?b(a[d]):a[d].toString();c[e]=a[d]}var d=[],f;for(f in c)d.push(c[f]);return d};function z(){var a,b,c=new Promise(function(c,e){a=c;b=e});c.resolve=a;c.reject=b;return c};function ra(a){return String.fromCharCode.apply(null,a)}n("shaka.util.Uint8ArrayUtils.toString",ra);function sa(a){for(var b=new Uint8Array(a.length),c=0;c<a.length;++c)b[c]=a.charCodeAt(c);return b}n("shaka.util.Uint8ArrayUtils.fromString",sa);function ta(a,b){var c=void 0==b?!0:b,d=window.btoa(ra(a)).replace(/\+/g,"-").replace(/\//g,"_");return c?d:d.replace(/=*$/,"")}n("shaka.util.Uint8ArrayUtils.toBase64",ta);function ua(a){return sa(window.atob(a.replace(/-/g,"+").replace(/_/g,"/")))}
n("shaka.util.Uint8ArrayUtils.fromBase64",ua);n("shaka.util.Uint8ArrayUtils.fromHex",function(a){for(var b=new Uint8Array(a.length/2),c=0;c<a.length;c+=2)b[c/2]=window.parseInt(a.substr(c,2),16);return b});function va(a){for(var b="",c=0;c<a.length;++c){var d=a[c].toString(16);1==d.length&&(d="0"+d);b+=d}return b}n("shaka.util.Uint8ArrayUtils.toHex",va);function la(a,b){if(!a&&!b)return!0;if(!a||!b||a.length!=b.length)return!1;for(var c=0;c<a.length;++c)if(a[c]!=b[c])return!1;return!0};function B(){this.a={}}B.prototype.push=function(a,b){this.a.hasOwnProperty(a)?this.a[a].push(b):this.a[a]=[b]};B.prototype.get=function(a){return(a=this.a[a])?a.slice():null};function xa(a){var b=[],c;for(c in a.a)b.push.apply(b,a.a[c]);return b}function ya(a,b,c){if(a=a.a[b])for(b=0;b<a.length;++b)a[b]==c&&(a.splice(b,1),--b)}function za(a){var b=[],c;for(c in a.a)b.push(c);return b};function Aa(){var a=Element.prototype;a.requestFullscreen=a.requestFullscreen||a.mozRequestFullScreen||a.msRequestFullscreen||a.webkitRequestFullscreen;a=Document.prototype;a.exitFullscreen=a.exitFullscreen||a.mozCancelFullScreen||a.msExitFullscreen||a.webkitExitFullscreen;"fullscreenElement"in document||Object.defineProperty(document,"fullscreenElement",{get:function(){return document.mozFullScreenElement||document.msFullscreenElement||document.webkitFullscreenElement}});document.addEventListener("webkitfullscreenchange",
Ba);document.addEventListener("webkitfullscreenerror",Ba);document.addEventListener("mozfullscreenchange",Ba);document.addEventListener("mozfullscreenerror",Ba);document.addEventListener("MSFullscreenChange",Ba);document.addEventListener("MSFullscreenError",Ba)}n("shaka.polyfill.Fullscreen.install",Aa);function Ba(a){var b=a.type.replace(/^(webkit|moz|MS)/,"").toLowerCase(),b=new Event(b,a);a.target.dispatchEvent(b)};function Ca(){var a="CustomEvent"in window;if(a)try{new CustomEvent("")}catch(b){a=!1}a||(window.CustomEvent=Da)}n("shaka.polyfill.CustomEvent.install",Ca);function Da(a,b){var c=document.createEvent("CustomEvent"),d=b||{bubbles:!1,cancelable:!1,detail:null};c.initCustomEvent(a,!!d.bubbles,!!d.cancelable,d.detail);return c};function Ea(){var a=HTMLVideoElement.prototype;!a.getVideoPlaybackQuality&&"webkitDroppedFrameCount"in a&&(a.getVideoPlaybackQuality=Fa)}n("shaka.polyfill.VideoPlaybackQuality.install",Ea);function Fa(){return{droppedVideoFrames:this.webkitDroppedFrameCount,totalVideoFrames:this.webkitDecodedFrameCount,corruptedVideoFrames:0,creationTime:NaN,totalFrameDelay:0}};function Ga(a){var b=console[a];b?b.bind||(console[a]=function(){b.apply(console,arguments)}):console[a]=function(){}}Ga("error");Ga("warn");Ga("info");Ga("log");Ga("debug");function Ha(){this.a=new B}Ha.prototype.destroy=function(){Ia(this);this.a=null};function C(a,b,c,d){b=new Ja(b,c,d);a.a.push(c,b)}Ha.prototype.na=function(a,b){for(var c=this.a.get(b)||[],d=0;d<c.length;++d){var e=c[d];e.target==a&&(e.na(),ya(this.a,b,e))}};function Ia(a){for(var b=xa(a.a),c=0;c<b.length;++c)b[c].na();a.a.a={}}function Ja(a,b,c){this.target=a;this.type=b;this.a=c;this.target.addEventListener(b,c,!1)}
Ja.prototype.na=function(){this.target&&(this.target.removeEventListener(this.type,this.a,!1),this.a=this.target=null)};function ia(a){var b=Ka;this.b=a;this.c=b==La;this.a=0}var Ka=0,La=1;function Ma(a){return a.a<a.b.byteLength}function oa(a){var b=a.b.getUint8(a.a);a.a+=1;return b}function D(a){var b=a.b.getUint32(a.a,a.c);a.a+=4;return b}function Na(a){var b,c;a.c?(b=a.b.getUint32(a.a,!0),c=a.b.getUint32(a.a+4,!0)):(c=a.b.getUint32(a.a,!1),b=a.b.getUint32(a.a+4,!1));if(2097151<c)throw new RangeError("DataViewReader: Overflow reading 64-bit value.");a.a+=8;return c*Math.pow(2,32)+b}
function Oa(a){if(a.a+16>a.b.byteLength)throw new RangeError("DataViewReader: Read past end of DataView.");var b=new Uint8Array(a.b.buffer,a.a,16);a.a+=16;return b}function ma(a,b){if(a.a+b>a.b.byteLength)throw new RangeError("DataViewReader: Skip past end of DataView.");a.a+=b};function Pa(a){this.systemIds=[];this.cencKeyIds=[];a=new ia(new DataView(a.buffer));try{for(;Ma(a);){var b=a.a,c=D(a),d=D(a);1==c?c=Na(a):0==c&&(c=a.b.byteLength-b);if(1886614376!=d)ma(a,c-(a.a-b));else{var e=oa(a);if(1<e)ma(a,c-(a.a-b));else{ma(a,3);var f=va(Oa(a)),g=[];if(0<e)for(var h=D(a),l=0;l<h;++l){var m=va(Oa(a));g.push(m)}var t=D(a);ma(a,t);this.cencKeyIds.push.apply(this.cencKeyIds,g);this.systemIds.push(f);a.a!=b+c&&ma(a,c-(a.a-b))}}}}catch(r){}};function G(a){var b=new CustomEvent(a.type,{detail:a.detail,bubbles:!!a.bubbles}),c;for(c in a)c in b||(b[c]=a[c]);return b}function H(a){return new CustomEvent("error",{detail:a,bubbles:!0})};function Qa(){this.g=new z;this.f=!1;this.a=null;this.b=[];this.c=null}function Ra(a,b){if(a.f)throw Error("Cannot append to a running task!");a.b.push(b)}Qa.prototype.start=function(){if(this.f)throw Error("Task already started!");this.f=!0;this.b.unshift(function(){});Sa(this,void 0)};Qa.prototype.end=function(){this.b.splice(1)};
function Sa(a,b){var c=a.b[0](b),d;c?(d=c[0],a.c=c[1]):(d=Promise.resolve(),a.c=null);d.then(v(a,function(a){this.a?(this.b=[],this.c=null,Ta(this)):(this.b.shift(),this.b.length?Sa(this,a):(this.g.resolve(a),this.c=null))})).catch(v(a,function(a){this.b=[];this.c=null;this.a?Ta(this):this.g.reject(a)}))}function Ta(a){var b=Error("Task aborted.");b.type="aborted";a.g.reject(b);window.setTimeout(function(){this.a.resolve();this.a=null}.bind(a),5)};function Ua(a,b,c){Va(b);Va(c);return c==b||a>=Wa&&c==b.split("-")[0]||a>=Xa&&c.split("-")[0]==b.split("-")[0]?!0:!1}var Wa=1,Xa=2;function Va(a){a=a.toLowerCase().split("-");var b=Ya[a[0]];b&&(a[0]=b);return a.join("-")}
var Ya={aar:"aa",abk:"ab",afr:"af",aka:"ak",alb:"sq",amh:"am",ara:"ar",arg:"an",arm:"hy",asm:"as",ava:"av",ave:"ae",aym:"ay",aze:"az",bak:"ba",bam:"bm",baq:"eu",bel:"be",ben:"bn",bih:"bh",bis:"bi",bod:"bo",bos:"bs",bre:"br",bul:"bg",bur:"my",cat:"ca",ces:"cs",cha:"ch",che:"ce",chi:"zh",chu:"cu",chv:"cv",cor:"kw",cos:"co",cre:"cr",cym:"cy",cze:"cs",dan:"da",deu:"de",div:"dv",dut:"nl",dzo:"dz",ell:"el",eng:"en",epo:"eo",est:"et",eus:"eu",ewe:"ee",fao:"fo",fas:"fa",fij:"fj",fin:"fi",fra:"fr",fre:"fr",
fry:"fy",ful:"ff",geo:"ka",ger:"de",gla:"gd",gle:"ga",glg:"gl",glv:"gv",gre:"el",grn:"gn",guj:"gu",hat:"ht",hau:"ha",heb:"he",her:"hz",hin:"hi",hmo:"ho",hrv:"hr",hun:"hu",hye:"hy",ibo:"ig",ice:"is",ido:"io",iii:"ii",iku:"iu",ile:"ie",ina:"ia",ind:"id",ipk:"ik",isl:"is",ita:"it",jav:"jv",jpn:"ja",kal:"kl",kan:"kn",kas:"ks",kat:"ka",kau:"kr",kaz:"kk",khm:"km",kik:"ki",kin:"rw",kir:"ky",kom:"kv",kon:"kg",kor:"ko",kua:"kj",kur:"ku",lao:"lo",lat:"la",lav:"lv",lim:"li",lin:"ln",lit:"lt",ltz:"lb",lub:"lu",
lug:"lg",mac:"mk",mah:"mh",mal:"ml",mao:"mi",mar:"mr",may:"ms",mkd:"mk",mlg:"mg",mlt:"mt",mon:"mn",mri:"mi",msa:"ms",mya:"my",nau:"na",nav:"nv",nbl:"nr",nde:"nd",ndo:"ng",nep:"ne",nld:"nl",nno:"nn",nob:"nb",nor:"no",nya:"ny",oci:"oc",oji:"oj",ori:"or",orm:"om",oss:"os",pan:"pa",per:"fa",pli:"pi",pol:"pl",por:"pt",pus:"ps",que:"qu",roh:"rm",ron:"ro",rum:"ro",run:"rn",rus:"ru",sag:"sg",san:"sa",sin:"si",slk:"sk",slo:"sk",slv:"sl",sme:"se",smo:"sm",sna:"sn",snd:"sd",som:"so",sot:"st",spa:"es",sqi:"sq",
srd:"sc",srp:"sr",ssw:"ss",sun:"su",swa:"sw",swe:"sv",tah:"ty",tam:"ta",tat:"tt",tel:"te",tgk:"tg",tgl:"tl",tha:"th",tib:"bo",tir:"ti",ton:"to",tsn:"tn",tso:"ts",tuk:"tk",tur:"tr",twi:"tw",uig:"ug",ukr:"uk",urd:"ur",uzb:"uz",ven:"ve",vie:"vi",vol:"vo",wel:"cy",wln:"wa",wol:"wo",xho:"xh",yid:"yi",yor:"yo",zha:"za",zho:"zh",zul:"zu"};function Za(a){this.c=Math.exp(Math.log(.5)/a);this.a=this.b=0}Za.prototype.sample=function(a,b){var c=Math.pow(this.c,a);this.b=b*(1-c)+c*this.b;this.a+=a};function $a(a){return a.b/(1-Math.pow(a.c,a.a))};function J(a){this.va=new B;this.o=a}n("shaka.util.FakeEventTarget",J);J.prototype.addEventListener=function(a,b,c){c||this.va.push(a,b)};J.prototype.removeEventListener=function(a,b,c){c||ya(this.va,a,b)};J.prototype.dispatchEvent=function(a){delete a.srcElement;delete a.target;delete a.currentTarget;Object.defineProperties(a,{srcElement:{value:null,writable:!0},target:{value:this,writable:!0},currentTarget:{value:null,writable:!0}});return ab(this,a)};
function ab(a,b){b.currentTarget=a;for(var c=a.va.get(b.type)||[],d=0;d<c.length;++d){var e=c[d];try{e.handleEvent?e.handleEvent(b):e.call(a,b)}catch(f){}}a.o&&b.bubbles&&ab(a.o,b);return b.defaultPrevented};function bb(){J.call(this,null);this.a=new Za(3);this.c=new Za(10);this.b=0}p(bb,J);n("shaka.util.EWMABandwidthEstimator",bb);bb.prototype.sample=function(a,b){if(!(65536>b)){a=Math.max(a,50);var c=8E3*b/a,d=a/1E3;this.a.sample(d,c);this.c.sample(d,c);this.dispatchEvent(G({type:"bandwidth"}));this.b=Date.now()}};bb.prototype.getBandwidth=function(){return.5>this.a.a?5E5:Math.min($a(this.a),$a(this.c))};bb.prototype.getDataAge=function(){return(Date.now()-this.b)/1E3};
bb.prototype.supportsCaching=function(){return!1};function cb(a,b){try{var c=new db(a,b);return Promise.resolve(c)}catch(d){return Promise.reject(d)}}function eb(a){var b=this.mediaKeys;b&&b!=a&&fb(b,null);delete this.mediaKeys;(this.mediaKeys=a)&&fb(a,this);return Promise.resolve()}
function db(a,b){this.a=this.keySystem=a;var c=!0;"org.w3.clearkey"==a&&(this.a="webkit-org.w3.clearkey",c=!1);var d=!1,e;e=document.getElementsByTagName("video");e=e.length?e[0]:document.createElement("video");for(var f=0;f<b.length;++f){var g=b[f],h={audioCapabilities:[],videoCapabilities:[],persistentState:"optional",distinctiveIdentifier:"optional",initDataTypes:g.initDataTypes},l=!1;if(g.audioCapabilities)for(var m=0;m<g.audioCapabilities.length;++m){var t=g.audioCapabilities[m];t.contentType&&
(l=!0,e.canPlayType(t.contentType.split(";")[0],this.a)&&(h.audioCapabilities.push(t),d=!0))}if(g.videoCapabilities)for(m=0;m<g.videoCapabilities.length;++m)t=g.videoCapabilities[m],t.contentType&&(l=!0,e.canPlayType(t.contentType,this.a)&&(h.videoCapabilities.push(t),d=!0));l||(d=e.canPlayType("video/mp4",this.a)||e.canPlayType("video/webm",this.a));"required"==g.persistentState&&(c?h.persistentState="required":d=!1);if(d){this.b=h;return}}throw Error("None of the requested configurations were supported.");
}db.prototype.createMediaKeys=function(){var a=new gb(this.a);return Promise.resolve(a)};db.prototype.getConfiguration=function(){return this.b};function gb(a){this.g=a;this.b=null;this.a=new Ha;this.c=[];this.f={}}function fb(a,b){a.b=b;Ia(a.a);b&&(C(a.a,b,"webkitneedkey",a.Gb.bind(a)),C(a.a,b,"webkitkeymessage",a.Fb.bind(a)),C(a.a,b,"webkitkeyadded",a.Db.bind(a)),C(a.a,b,"webkitkeyerror",a.Eb.bind(a)))}k=gb.prototype;
k.createSession=function(a){var b=a||"temporary";if("temporary"!=b&&"persistent-license"!=b)throw new TypeError("Session type "+a+" is unsupported on this platform.");a=this.b||document.createElement("video");a.src||(a.src="about:blank");b=new hb(a,this.g,b);this.c.push(b);return b};k.setServerCertificate=function(){return Promise.reject(Error("setServerCertificate not supported on this platform."))};k.Gb=function(a){a=G({type:"encrypted",initDataType:"webm",initData:a.initData});this.b.dispatchEvent(a)};
k.Fb=function(a){var b=ib(this,a.sessionId);b&&(a=G({type:"message",messageType:void 0==b.keyStatuses.a?"licenserequest":"licenserenewal",message:a.message}),b.b&&(b.b.resolve(),b.b=null),b.dispatchEvent(a))};k.Db=function(a){if(a=ib(this,a.sessionId))jb(a,"usable"),a.a&&a.a.resolve(),a.a=null};
k.Eb=function(a){var b=ib(this,a.sessionId);if(b){var c=Error("EME v0.1b key error");c.errorCode=a.errorCode;c.errorCode.systemCode=a.systemCode;!a.sessionId&&b.b?(c.method="generateRequest",45==a.systemCode&&(c.message="Unsupported session type."),b.b.reject(c),b.b=null):a.sessionId&&b.a?(c.method="update",b.a.reject(c),b.a=null):(c=a.systemCode,a.errorCode.code==MediaKeyError.MEDIA_KEYERR_OUTPUT?jb(b,"output-not-allowed"):1==c?jb(b,"expired"):jb(b,"internal-error"))}};
function ib(a,b){var c=a.f[b];return c?c:(c=a.c.shift())?(c.sessionId=b,a.f[b]=c):null}function hb(a,b,c){J.call(this,null);this.f=a;this.h=!1;this.a=this.b=null;this.c=b;this.g=c;this.sessionId="";this.expiration=NaN;this.closed=new z;this.keyStatuses=new kb}p(hb,J);
function lb(a,b,c){if(a.h)return Promise.reject(Error("The session is already initialized."));a.h=!0;var d;try{if("persistent-license"==a.g)if(c)d=sa("LOAD_SESSION|"+c);else{var e=new Uint8Array(b);d=sa("PERSISTENT|"+ra(e))}else d=new Uint8Array(b)}catch(f){return Promise.reject(f)}a.b=new z;try{a.f.webkitGenerateKeyRequest(a.c,d)}catch(g){if("InvalidStateError"!=g.name)return a.b=null,Promise.reject(g);setTimeout(function(){try{this.f.webkitGenerateKeyRequest(this.c,d)}catch(a){this.b.reject(a),
this.b=null}}.bind(a),10)}return a.b}k=hb.prototype;
k.Ia=function(a,b){if(this.a)this.a.then(this.Ia.bind(this,a,b)).catch(this.Ia.bind(this,a,b));else{this.a=a;var c,d;if("webkit-org.w3.clearkey"==this.c){c=ra(new Uint8Array(b));d=JSON.parse(c);c=d.keys[0].kty;if("A128KW"!=d.keys[0].alg||"oct"!=c)this.a.reject(Error("Response is not a valid JSON Web Key Set.")),this.a=null;c=ua(d.keys[0].k);d=ua(d.keys[0].kid)}else c=new Uint8Array(b),d=null;try{this.f.webkitAddKey(this.c,c,d,this.sessionId)}catch(e){this.a.reject(e),this.a=null}}};
function jb(a,b){var c=a.keyStatuses;c.size=void 0==b?0:1;c.a=b;c=G({type:"keystatuseschange"});a.dispatchEvent(c)}k.generateRequest=function(a,b){return lb(this,b,null)};k.load=function(a){return"persistent-license"==this.g?lb(this,null,a):Promise.reject(Error("Not a persistent session."))};k.update=function(a){var b=new z;this.Ia(b,a);return b};
k.close=function(){if("persistent-license"!=this.g){if(!this.sessionId)return this.closed.reject(Error("The session is not callable.")),this.closed;this.f.webkitCancelKeyRequest(this.c,this.sessionId)}this.closed.resolve();return this.closed};k.remove=function(){return"persistent-license"!=this.g?Promise.reject(Error("Not a persistent session.")):this.close()};function mb(a){this.b=a;this.a=0}
mb.prototype.next=function(){return this.a>=this.b.length?{value:void 0,done:!0}:{value:this.b[this.a++],done:!1}};function kb(){this.size=0;this.a=void 0}var nb;k=kb.prototype;k.entries=function(){var a=nb,b=[];this.a&&b.push([a,this.a]);return new mb(b)};k.forEach=function(a){this.a&&a(this.a)};k.get=function(a){if(this.has(a))return this.a};k.has=function(a){var b=nb;return this.a&&la(new Uint8Array(a),b)?!0:!1};k.keys=function(){var a=nb,b=[];this.a&&b.push(a);return new mb(b)};
k.values=function(){var a=[];this.a&&a.push(this.a);return new mb(a)};function ob(){return Promise.reject(Error("The key system specified is not supported."))}function pb(a){return null==a?Promise.resolve():Promise.reject(Error("MediaKeys not supported."))}function qb(){throw new TypeError("Illegal constructor.");}qb.prototype.createSession=function(){};qb.prototype.setServerCertificate=function(){};function rb(){throw new TypeError("Illegal constructor.");}rb.prototype.getConfiguration=function(){};rb.prototype.createMediaKeys=function(){};function sb(){Navigator.prototype.requestMediaKeySystemAccess&&MediaKeySystemAccess.prototype.getConfiguration||(HTMLMediaElement.prototype.webkitGenerateKeyRequest?(nb=sa("FAKE_KEY_ID"),Navigator.prototype.requestMediaKeySystemAccess=cb,delete HTMLMediaElement.prototype.mediaKeys,HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=eb,window.MediaKeys=gb,window.MediaKeySystemAccess=db):(Navigator.prototype.requestMediaKeySystemAccess=ob,delete HTMLMediaElement.prototype.mediaKeys,
HTMLMediaElement.prototype.mediaKeys=null,HTMLMediaElement.prototype.setMediaKeys=pb,window.MediaKeys=qb,window.MediaKeySystemAccess=rb))}n("shaka.polyfill.MediaKeys.install",sb);n("shaka.polyfill.installAll",function(){Ca();Aa();sb();Ea()});function tb(a){ub[a]={ia:vb(),end:NaN}}function wb(a){if(a=ub[a])a.end=vb()}function xb(a){return(a=ub[a])&&a.end?a.end-a.ia:NaN}var vb=window.performance&&window.performance.now?window.performance.now.bind(window.performance):Date.now,ub={};function yb(a,b,c,d){this.id=a;this.bandwidth=b||0;this.width=c||0;this.height=d||0;this.active=!1}function zb(a,b){var c=a.width*a.height,d=b.width*b.height;return c<d?-1:c>d?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0}n("shaka.player.VideoTrack.compare",zb);function Ab(a,b){this.id=a;this.lang=b||"unknown";this.enabled=this.active=!1}n("shaka.player.TextTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:0});function K(){this.fontSize="100%";this.fontColor=Bb;this.fontOpacity=Cb;this.backgroundColor=Db;this.backgroundOpacity=Cb;this.fontEdge=Eb}n("shaka.player.TextStyle",K);K.prototype.a=function(){var a=window.localStorage.getItem("ShakaPlayerTextStyle");if(a){var b;try{b=JSON.parse(a)}catch(c){return}if(b&&"object"==typeof b){var a=b,d;for(d in a)d in this&&(this[d]=a[d])}}};K.prototype.load=K.prototype.a;K.prototype.b=function(){window.localStorage.setItem("ShakaPlayerTextStyle",JSON.stringify(this))};
K.prototype.store=K.prototype.b;function Fb(a){var b=[];b.push("font-size: "+a.fontSize);b.push("color: "+Gb(a.fontColor,a.fontOpacity));b.push("background-color: "+Gb(a.backgroundColor,a.backgroundOpacity));for(var c=[],d=0;d<a.fontEdge.length;++d){var e=a.fontEdge[d].slice(3,6);c.push(Gb(a.fontEdge[d].slice(0,3),a.fontOpacity)+" "+e.join("px ")+"px")}b.push("text-shadow: "+c.join(","));return b.join("; ")}function Gb(a,b){return"rgba("+a.concat(b).join(",")+")"}var Bb=[255,255,255],Db=[0,0,0];
K.StandardColors={WHITE:Bb,BLACK:Db,RED:[255,0,0],GREEN:[0,255,0],BLUE:[0,0,255],YELLOW:[255,255,0],MAGENTA:[255,0,255],CYAN:[0,255,255]};var Cb=1;K.StandardOpacities={OPAQUE:Cb,SEMI_HIGH:.75,SEMI_LOW:.25,TRANSPARENT:0};var Eb=[];
K.EdgeStyles={NONE:Eb,RAISED:[[34,34,34,1,1,0],[34,34,34,2,2,0],[34,34,34,3,3,0]],DEPRESSED:[[204,204,204,1,1,0],[204,204,204,0,1,0],[34,34,34,-1,-1,0],[34,34,34,0,-1,0]],UNIFORM:[[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4],[34,34,34,0,0,4]],DROP:[[34,34,34,2,2,3],[34,34,34,2,2,4],[34,34,34,2,2,5]]};function Hb(a,b,c){this.id=a;this.bandwidth=b||0;this.lang=c||"unknown";this.active=!1}n("shaka.player.AudioTrack.compare",function(a,b){return a.lang<b.lang?-1:a.lang>b.lang?1:a.bandwidth<b.bandwidth?-1:a.bandwidth>b.bandwidth?1:0});function Ib(a,b,c,d,e,f,g,h,l,m,t){this.b=a;this.o=b;this.u=c;this.a=[];this.c=e||null;this.f=f||null;this.i=g==Jb;this.m=h==Kb;this.h=l||"";this.v=m||"";this.g=t||null;d&&this.a.push(d)}n("shaka.player.DrmSchemeInfo",Ib);var Jb=1;Ib.DistinctiveIdentifier={OPTIONAL:0,REQUIRED:Jb};var Kb=1;Ib.PersistentState={OPTIONAL:0,REQUIRED:Kb};function Lb(){this.minBandwidth=this.maxBandwidth=this.maxWidth=this.maxHeight=null}
Lb.prototype.clone=function(){var a=new Lb;a.maxHeight=this.maxHeight;a.maxWidth=this.maxWidth;a.maxBandwidth=this.maxBandwidth;a.minBandwidth=this.minBandwidth;return a};function Mb(){return new Ib("","",!1,null)}Ib.createUnencrypted=Mb;function Nb(a,b){a.a=qa(a.a.concat(b.a),function(a){return Array.prototype.join.apply(a.initData)})}Ib.combine=Nb;Ib.prototype.key=function(){return JSON.stringify(this)};var Ob=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/;function L(a){var b;a instanceof L?(Pb(this,a.O),this.W=a.W,this.N=a.N,Qb(this,a.ca),this.J=a.J,Rb(this,a.a.clone()),this.U=a.U):a&&(b=String(a).match(Ob))?(Pb(this,b[1]||"",!0),this.W=Sb(b[2]||""),this.N=Sb(b[3]||"",!0),Qb(this,b[4]),this.J=Sb(b[5]||"",!0),Rb(this,b[6]||"",!0),this.U=Sb(b[7]||"")):this.a=new Tb(null)}k=L.prototype;k.O="";k.W="";k.N="";k.ca=null;k.J="";k.U="";
k.toString=function(){var a=[],b=this.O;b&&a.push(Ub(b,Vb,!0),":");if(b=this.N){a.push("//");var c=this.W;c&&a.push(Ub(c,Vb,!0),"@");a.push(encodeURIComponent(b).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ca;null!=b&&a.push(":",String(b))}if(b=this.J)this.N&&"/"!=b.charAt(0)&&a.push("/"),a.push(Ub(b,"/"==b.charAt(0)?Wb:Xb,!0));(b=this.a.toString())&&a.push("?",b);(b=this.U)&&a.push("#",Ub(b,Yb));return a.join("")};
k.resolve=function(a){var b=this.clone(),c=!!a.O;c?Pb(b,a.O):c=!!a.W;c?b.W=a.W:c=!!a.N;c?b.N=a.N:c=null!=a.ca;var d=a.J;if(c)Qb(b,a.ca);else if(c=!!a.J){if("/"!=d.charAt(0))if(this.N&&!this.J)d="/"+d;else{var e=b.J.lastIndexOf("/");-1!=e&&(d=b.J.substr(0,e+1)+d)}if(".."==d||"."==d)d="";else if(-1!=d.indexOf("./")||-1!=d.indexOf("/.")){for(var e=0==d.lastIndexOf("/",0),d=d.split("/"),f=[],g=0;g<d.length;){var h=d[g++];"."==h?e&&g==d.length&&f.push(""):".."==h?((1<f.length||1==f.length&&""!=f[0])&&
f.pop(),e&&g==d.length&&f.push("")):(f.push(h),e=!0)}d=f.join("/")}}c?b.J=d:c=""!==a.a.toString();c?Rb(b,a.a.clone()):c=!!a.U;c&&(b.U=a.U);return b};k.clone=function(){return new L(this)};function Pb(a,b,c){a.O=c?Sb(b,!0):b;a.O&&(a.O=a.O.replace(/:$/,""))}function Qb(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.ca=b}else a.ca=null}function Rb(a,b,c){b instanceof Tb?a.a=b:(c||(b=Ub(b,Zb)),a.a=new Tb(b))}
function Sb(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""}function Ub(a,b,c){return"string"==typeof a?(a=encodeURI(a).replace(b,$b),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null}function $b(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)}var Vb=/[#\/\?@]/g,Xb=/[\#\?:]/g,Wb=/[\#\?]/g,Zb=/[\#\?@]/g,Yb=/#/g;function Tb(a){this.b=a||null}Tb.prototype.a=null;Tb.prototype.c=null;
function ac(a,b,c){if(!a.a&&(a.a={},a.c=0,a.b))for(var d=a.b.split("&"),e=0;e<d.length;e++){var f=d[e].indexOf("="),g=null,h=null;0<=f?(g=d[e].substring(0,f),h=d[e].substring(f+1)):g=d[e];g=decodeURIComponent(g.replace(/\+/g," "));h=h||"";ac(a,g,decodeURIComponent(h.replace(/\+/g," ")))}a.b=null;(d=a.a.hasOwnProperty(b)&&a.a[b])||(a.a[b]=d=[]);d.push(c);a.c++}
Tb.prototype.toString=function(){if(this.b)return this.b;if(!this.a)return"";var a=[],b;for(b in this.a)for(var c=encodeURIComponent(b),d=this.a[b],e=0;e<d.length;e++){var f=c;""!==d[e]&&(f+="="+encodeURIComponent(d[e]));a.push(f)}return this.b=a.join("&")};Tb.prototype.clone=function(){var a=new Tb;a.b=this.b;if(this.a){var b={},c;for(c in this.a)b[c]=this.a[c].concat();a.a=b;a.c=this.c}return a};function bc(a){this.url=a;this.a=new cc;this.g=this.i=this.h=0;this.b=null;this.c=new z;this.f=null}function cc(){this.body=null;this.a=1;this.g=1E3;this.c=0;this.method="GET";this.f="arraybuffer";this.b={};this.i=this.h=!1}function dc(a){ec(a);a.a.body=null;a.c=null;a.f=null}function ec(a){a.b&&(a.b.onload=null,a.b.onreadystatechange=null,a.b.onerror=null,a.b.ontimeout=null);a.b=null}k=bc.prototype;
k.sa=function(){if(this.b)return this.c;if(0==this.url.lastIndexOf("data:",0)){var a=this.url.split(":")[1].split(";").pop().split(","),b=a.pop(),b="base64"==a.pop()?window.atob(b.replace(/-/g,"+").replace(/_/g,"/")):window.decodeURIComponent(b);"arraybuffer"==this.a.f&&(b=sa(b).buffer);a=JSON.parse(JSON.stringify(new XMLHttpRequest));a.response=b;a.responseText=b.toString();b=this.c;b.resolve(a);dc(this);return b}if(0==this.url.lastIndexOf("idb:",0))return fc(this);this.h++;this.i=Date.now();this.g||
(this.g=this.a.g);this.b=new XMLHttpRequest;a=this.url;this.f&&!this.f.supportsCaching()&&(a=new L(a),ac(a.a,"_",Date.now()),a=a.toString());this.b.open(this.a.method,a,!0);this.b.responseType=this.a.f;this.b.timeout=this.a.c;this.b.withCredentials=this.a.h;this.b.onload=this.qb.bind(this);this.a.i&&(this.b.onreadystatechange=this.ub.bind(this));this.b.onerror=this.Nb.bind(this);this.b.ontimeout=this.zb.bind(this);for(b in this.a.b)this.b.setRequestHeader(b,this.a.b[b]);this.b.send(this.a.body);return this.c};
function fc(a){var b=a.url.split("/"),c=parseInt(b[2],10),d=parseInt(b[3],10),e=new gc(null,null);return hc(e).then(function(){return ic(e,c,d)}).then(v(a,function(a){var b=JSON.parse(JSON.stringify(new XMLHttpRequest));b.response=a;a=this.c;a.resolve(b);M(e);dc(this);return a})).catch(v(a,function(a){M(e);dc(this);return Promise.reject(a)}))}function jc(a,b,c){b=Error(b);b.type=c;b.status=a.b.status;b.url=a.url;b.method=a.a.method;b.body=a.a.body;b.Sb=a.b;return b}
k.ab=function(){if(this.b&&this.b.readyState!=XMLHttpRequest.DONE){this.b.abort();var a=jc(this,"Request aborted.","aborted");this.c.reject(a);dc(this)}};k.qb=function(a){this.f&&this.f.sample(Date.now()-this.i,a.loaded);200<=this.b.status&&299>=this.b.status?(this.c.resolve(this.b),dc(this)):this.h<this.a.a?kc(this):(a=jc(this,"HTTP error.","net"),this.c.reject(a),dc(this))};
k.ub=function(){if(this.b.readyState==XMLHttpRequest.HEADERS_RECEIVED){var a=Date.parse(this.b.getResponseHeader("Date"));a&&(ca=a-Date.now())}};k.Nb=function(){var a=jc(this,"Network failure.","net");this.c.reject(a);dc(this)};k.zb=function(){if(this.h<this.a.a)kc(this);else{var a=jc(this,"Request timed out.","net");this.c.reject(a);dc(this)}};function kc(a){ec(a);window.setTimeout(a.sa.bind(a),a.g*(1+.5*(2*Math.random()-1)));a.g*=2};function lc(a,b,c,d,e,f){bc.call(this,a);if(b||c)this.a.b.Range="bytes="+(b+"-"+(null!=c?c:""));d&&(this.a.a=d);e&&(this.a.g=e);this.a.c=1E3*(null!=f?f:0)}p(lc,bc);function mc(a){return a.sa().then(v(a,function(a){return Promise.resolve(a.response)}))};function nc(a,b,c,d,e,f){bc.call(this,a);this.a.body=b;this.a.method=c;this.a.a=3;this.a.h=d;this.a.c=1E3*(null!=f?f:0);a=e||{};for(var g in a)this.a.b[g]=a[g]}p(nc,bc);function oc(a){return a.sa().then(function(a){return Promise.resolve(new Uint8Array(a.response))})};function pc(){this.id=this.url=null;this.type="static";this.c=this.o=this.j=null;this.h=5;this.f=this.b=this.g=null;this.i=1;this.a=[]}function qc(){this.g=this.f=this.c=this.j=this.a=this.start=this.id=null;this.b=[]}function rc(){this.o=this.b=this.height=this.width=this.contentType=this.lang=this.c=this.id=null;this.f=!1;this.i=this.h=this.g=this.j=null;this.m=[];this.a=[]}function sc(){this.value=null}function tc(){this.contentType=this.lang=this.id=null}
function uc(){this.a=this.b=this.f=this.j=this.h=this.c=this.height=this.width=this.bandwidth=this.lang=this.id=null;this.g=[]}function vc(){this.value=this.schemeIdUri=null;this.children=[];this.pssh=null}function wc(){this.parsedPssh=this.psshBox=null}function xc(){this.url=null}function yc(){this.url=null}function zc(){this.j=null;this.g=1;this.c=this.b=this.a=this.f=null}
zc.prototype.clone=function(){var a=new zc;a.j=this.j?new L(this.j):null;a.g=this.g;a.f=this.f;a.a=N(this.a);a.b=N(this.b);a.c=N(this.c);return a};function Ac(){this.a=this.url=null}Ac.prototype.clone=function(){var a=new Ac;a.url=this.url?new L(this.url):null;a.a=N(this.a);return a};function Bc(){this.a=this.url=null}Bc.prototype.clone=function(){var a=new Bc;a.url=this.url?new L(this.url):null;a.a=N(this.a);return a};
function Cc(){this.j=null;this.f=1;this.b=this.i=null;this.h=1;this.g=null;this.a=[];this.c=null}Cc.prototype.clone=function(){var a=new Cc;a.j=this.j?new L(this.j):null;a.f=this.f;a.i=this.i;a.b=this.b;a.h=this.h;a.g=N(this.g);a.a=this.a.map(function(a){return a.clone()});a.c=N(this.c);return a};function Dc(){this.a=this.b=null}Dc.prototype.clone=function(){var a=new Dc;a.b=this.b?new L(this.b):null;a.a=N(this.a);return a};
function Ec(){this.b=1;this.a=this.o=null;this.i=1;this.c=this.g=this.f=this.h=null}Ec.prototype.clone=function(){var a=new Ec;a.b=this.b;a.o=this.o;a.a=this.a;a.i=this.i;a.h=this.h;a.f=this.f;a.g=this.g;a.c=N(this.c);return a};function Fc(){this.a=[]}Fc.prototype.clone=function(){var a=new Fc;a.a=this.a.map(function(a){return a.clone()});return a};function Gc(){this.b=this.a=this.c=null}Gc.prototype.clone=function(){var a=new Gc;a.c=this.c;a.a=this.a;a.b=this.b;return a};
function Hc(a,b){this.ia=a;this.end=b}Hc.prototype.clone=function(){return new Hc(this.ia,this.end)};pc.TAG_NAME="MPD";qc.TAG_NAME="Period";rc.TAG_NAME="AdaptationSet";sc.TAG_NAME="Role";tc.TAG_NAME="ContentComponent";uc.TAG_NAME="Representation";vc.TAG_NAME="ContentProtection";wc.TAG_NAME="cenc:pssh";xc.TAG_NAME="BaseURL";yc.TAG_NAME="Location";zc.TAG_NAME="SegmentBase";Ac.TAG_NAME="RepresentationIndex";Bc.TAG_NAME="Initialization";Cc.TAG_NAME="SegmentList";Dc.TAG_NAME="SegmentURL";Ec.TAG_NAME="SegmentTemplate";
Fc.TAG_NAME="SegmentTimeline";Gc.TAG_NAME="S";
pc.prototype.parse=function(a,b){this.url=new L(a.j);this.id=O(b,"id",P);this.type=O(b,"type",P)||"static";this.c=O(b,"mediaPresentationDuration",Ic);this.h=O(b,"minBufferTime",Ic,this.h);this.g=O(b,"minimumUpdatePeriod",Ic,this.g);this.b=O(b,"availabilityStartTime",Jc,this.b);this.f=O(b,"timeShiftBufferDepth",Ic,this.f);this.i=O(b,"suggestedPresentationDelay",Ic,this.i);var c=Q(this,b,xc);this.j=Kc(a.j,c?c.url:null);if(c=Q(this,b,yc))this.o=Kc(a.j,c.url);this.a=Lc(this,b,qc)};
qc.prototype.parse=function(a,b){this.id=O(b,"id",P);this.start=O(b,"start",Ic);this.a=O(b,"duration",Ic);var c=Q(this,b,xc);this.j=Kc(a.j,c?c.url:null);this.c=Q(this,b,zc);this.f=Q(this,b,Cc);this.g=Q(this,b,Ec);this.b=Lc(this,b,rc);Mc(this)};function Mc(a){for(var b=[],c=0;c<a.b.length;++c){var d=a.b[c];null!=d.c&&(b[d.c]=!0)}for(c=0;c<a.b.length;++c)if(d=a.b[c],null==d.c){for(var e=1;1==b[e];)++e;b[e]=!0;d.c=e}}
rc.prototype.parse=function(a,b){var c=Q(this,b,tc)||{},d=Q(this,b,sc);this.id=O(b,"id",P);this.c=O(b,"group",R);this.lang=O(b,"lang",P,c.lang);this.contentType=O(b,"contentType",P,c.contentType);this.width=O(b,"width",S);this.height=O(b,"height",S);this.b=O(b,"mimeType",P);this.o=O(b,"codecs",P);this.f=d&&"main"==d.value;this.lang&&(this.lang=Va(this.lang));c=Q(this,b,xc);this.j=Kc(a.j,c?c.url:null);this.m=Lc(this,b,vc);!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]);this.g=a.c?
Nc(this,b,a.c):Q(this,b,zc);this.h=a.f?Nc(this,b,a.f):Q(this,b,Cc);this.i=a.g?Nc(this,b,a.g):Q(this,b,Ec);this.a=Lc(this,b,uc);!this.b&&this.a.length&&(this.b=this.a[0].c,!this.contentType&&this.b&&(this.contentType=this.b.split("/")[0]))};sc.prototype.parse=function(a,b){this.value=O(b,"value",P)};tc.prototype.parse=function(a,b){this.id=O(b,"id",P);this.lang=O(b,"lang",P);this.contentType=O(b,"contentType",P);this.lang&&(this.lang=Va(this.lang))};
uc.prototype.parse=function(a,b){this.id=O(b,"id",P);this.bandwidth=O(b,"bandwidth",S);this.width=O(b,"width",S,a.width);this.height=O(b,"height",S,a.height);this.c=O(b,"mimeType",P,a.b);this.h=O(b,"codecs",P,a.o);this.lang=a.lang;var c=Q(this,b,xc);this.j=Kc(a.j,c?c.url:null);this.g=Lc(this,b,vc);this.f=a.g?Nc(this,b,a.g):Q(this,b,zc);this.b=a.h?Nc(this,b,a.h):Q(this,b,Cc);this.a=a.i?Nc(this,b,a.i):Q(this,b,Ec);0==this.g.length&&(this.g=a.m)};
vc.prototype.parse=function(a,b){this.schemeIdUri=O(b,"schemeIdUri",P);this.value=O(b,"value",P);this.pssh=Q(this,b,wc);this.children=Array.prototype.slice.call(b.childNodes)};wc.prototype.parse=function(a,b){var c=Oc(b);if(c){this.psshBox=ua(c);try{this.parsedPssh=new Pa(this.psshBox)}catch(d){if(!(d instanceof RangeError))throw d;}}};xc.prototype.parse=function(a,b){this.url=Oc(b)};yc.prototype.parse=function(a,b){this.url=Oc(b)};
zc.prototype.parse=function(a,b){this.j=a.j||this.j;this.g=O(b,"timescale",S,this.g);this.f=O(b,"presentationTimeOffset",R,this.f);this.a=O(b,"indexRange",Pc,this.a);this.b=Q(this,b,Ac)||this.b;this.c=Q(this,b,Bc)||this.c};Ac.prototype.parse=function(a,b){var c=O(b,"sourceURL",P);this.url=Kc(a.j,c);this.a=O(b,"range",Pc,N(a.a))};Bc.prototype.parse=function(a,b){var c=O(b,"sourceURL",P);this.url=Kc(a.j,c);this.a=O(b,"range",Pc)};
Cc.prototype.parse=function(a,b){this.j=a.j||this.j;this.f=O(b,"timescale",S,this.f);this.i=O(b,"presentationTimeOffset",R,this.i);this.b=O(b,"duration",S,this.b);this.h=O(b,"startNumber",R,this.h);this.g=Q(this,b,Bc)||this.g;this.a=Lc(this,b,Dc)||this.a;this.c=Q(this,b,Fc)||this.c};Dc.prototype.parse=function(a,b){var c=O(b,"media",P);this.b=Kc(a.j,c);this.a=O(b,"mediaRange",Pc)};
Ec.prototype.parse=function(a,b){this.b=O(b,"timescale",S,this.b);this.o=O(b,"presentationTimeOffset",R,this.o);this.a=O(b,"duration",S,this.a);this.i=O(b,"startNumber",R,this.i);this.h=O(b,"media",P,this.h);this.f=O(b,"index",P,this.f);this.g=O(b,"initialization",P,this.g);this.c=Q(this,b,Fc)||this.c};Fc.prototype.parse=function(a,b){this.a=Lc(this,b,Gc)};Gc.prototype.parse=function(a,b){this.c=O(b,"t",R);this.a=O(b,"d",R);this.b=O(b,"r",R)};
function Kc(a,b){var c=b?new L(b):null;return a?c?a.resolve(c):a:c}function Nc(a,b,c){var d=N(c);(b=Qc(b,c.constructor.TAG_NAME))&&d.parse(a,b);return d}function Q(a,b,c){var d=null;if(b=Qc(b,c.TAG_NAME))d=new c,d.parse(a,b);return d}function Qc(a,b){for(var c=null,d=0;d<a.childNodes.length;d++)if(a.childNodes[d].tagName==b){if(c)return null;c=a.childNodes[d]}return c}
function Lc(a,b,c){for(var d=[],e=0;e<b.childNodes.length;e++)if(b.childNodes[e].tagName==c.TAG_NAME){var f=new c;f.parse.call(f,a,b.childNodes[e]);d.push(f)}return d}function Oc(a){a=a.firstChild;return a.nodeType!=Node.TEXT_NODE?null:a.nodeValue}function N(a){return a?a.clone():null}function O(a,b,c,d){a=c(a.getAttribute(b));return null!=a?a:void 0!==d?d:null}function Jc(a){if(!a)return null;a=Date.parse(a);return isNaN(a)?null:Math.floor(a/1E3)}
function Ic(a){if(!a)return null;var b=/^P(?:([0-9]*)Y)?(?:([0-9]*)M)?(?:([0-9]*)D)?(?:T(?:([0-9]*)H)?(?:([0-9]*)M)?(?:([0-9.]*)S)?)?$/.exec(a);if(!b)return null;a=0;var c=R(b[1]);c&&(a+=31536E3*c);(c=R(b[2]))&&(a+=2592E3*c);(c=R(b[3]))&&(a+=86400*c);(c=R(b[4]))&&(a+=3600*c);(c=R(b[5]))&&(a+=60*c);b=window.parseFloat(b[6]);(b=isNaN(b)?null:b)&&(a+=b);return a}
function Pc(a){var b=/([0-9]+)-([0-9]+)/.exec(a);if(!b)return null;a=R(b[1]);if(null==a)return null;b=R(b[2]);return null==b?null:new Hc(a,b)}function S(a){a=window.parseInt(a,10);return 0<a?a:null}function R(a){a=window.parseInt(a,10);return 0<=a?a:null}function P(a){return a};function Rc(a,b){bc.call(this,a);this.a.f="text";this.a.a=3;this.a.c=1E3*(null!=b?b:0);this.a.i=!0}p(Rc,bc);function Sc(a){var b=a.url;return a.sa().then(function(a){a=a.responseText;if(a=(new DOMParser).parseFromString(a,"text/xml")){var d={j:new L(b)};a=Q(d,a,pc)}else a=null;if(a)return Promise.resolve(a);a=Error("MPD parse failure.");a.type="mpd";return Promise.reject(a)})};function Tc(a,b,c){for(var d=a.a,e=[],f=0;f<c;++f){var g=f+b,h=(g-1)*d.a,l=h/d.b,h=(h+d.a)/d.b,g=Uc(a,g-1+d.i,(g-1)*d.a);if(!g)return null;e.push(new Vc(l,h,0,null,new L(g)))}return e}function Uc(a,b,c){if(!a.a)return null;var d=a.a.h;return d?(b=Wc(d,a.id,b,a.bandwidth,c))?a.j?a.j.resolve(b):b:null:a.j?new L(a.j):null}
function Wc(a,b,c,d,e){var f={RepresentationID:b,Number:c,Bandwidth:d,Time:e};a=a.replace(/\$(RepresentationID|Number|Bandwidth|Time)?(?:%0([0-9]+)d)?\$/g,function(a,b,c){if("$$"==a)return"$";var d=f[b];if(null==d)return a;"RepresentationID"==b&&c&&(c=void 0);a=d.toString();c=window.parseInt(c,10)||1;c=Math.max(0,c-a.length);return Array(c+1).join("0")+a});try{return new L(a)}catch(g){if(g instanceof URIError)return null;throw g;}}
function Xc(a){var b=0;a=a.a;for(var c=[],d=0;d<a.length&&a[d].a;++d)for(var e=a[d].c,e=null!=e?e:b,f=a[d].b||0,g=0;g<=f;++g){var h=e+a[d].a;0<c.length&&e!=b&&(c[c.length-1].end=e);c.push({start:e,end:h});b=e=h}return c};function Yc(a,b,c){this.i=a;this.c=b;this.o=c;this.h=new Ha;this.b=[];this.u=0;this.f=this.a=null;this.m=0;C(this.h,this.c,"updateend",this.v.bind(this))}var Zc=1/60;Yc.prototype.destroy=function(){$c(this);this.b=this.a=this.f=null;this.h.destroy();this.i=this.c=this.h=null};function ad(a,b){for(var c=a.c.buffered,d=0;d<c.length;++d){var e=c.start(d)-Zc,f=c.end(d)+Zc;if(b>=e&&b<=f)return c.end(d)-b}return 0}
function bd(a,b,c){if(a.a)return a=Error("Cannot fetch: previous operation not complete."),a.type="stream",Promise.reject(a);a.a=new Qa;c&&Ra(a.a,function(){return[cd(this,c),this.g.bind(this)]}.bind(a));Ra(a.a,function(){var a=new lc(b.url.toString(),b.c,b.f,3,1E3*(b.a?b.a-b.b:1),this.m);a.f=this.o;return[mc(a),a.ab.bind(a)]}.bind(a));Ra(a.a,v(a,function(a){this.o.getBandwidth();return[cd(this,a),this.g.bind(this)]}));var d=0==a.c.buffered.length&&0==a.b.length,e=null;Ra(a.a,function(){if(d){var a=
b.b;e=this.c.buffered.start(0)-a}a=dd(this.b,b.b);0<=a?this.b.splice(a+1,0,b):this.b.push(b)}.bind(a));return ed(a).then(function(){return Promise.resolve(e)}.bind(a))}
function fd(a){if(a.a)return a=Error("Cannot clear: previous operation not complete."),a.type="stream",Promise.reject(a);a.a=new Qa;Ra(a.a,function(){var a;a:if(0==this.c.buffered.length)a=Promise.resolve();else{try{this.c.remove(0,Number.POSITIVE_INFINITY)}catch(c){a=Promise.reject(c);break a}this.b=[];a=this.f=new z}return[a,this.g.bind(this)]}.bind(a));return ed(a)}function $c(a){a.a?(a=a.a,a.a?a=a.a:a.f?(a.c&&a.c(),a.a=new z,a=a.a):(a.f=!0,a=Promise.resolve())):a=Promise.resolve();return a}
function ed(a){a.a.start();return a.a.g.then(v(a,function(){this.a=null})).catch(v(a,function(a){this.a=null;return Promise.reject(a)}))}function cd(a,b){try{a.c.appendBuffer(b)}catch(c){return Promise.reject(c)}a.f=new z;return a.f}Yc.prototype.g=function(){"open"==this.i.readyState&&this.c.abort()};Yc.prototype.v=function(){this.f.resolve();this.f=null};function gd(a,b,c){this.url=a;this.c=b;this.f=c;this.b=this.a=null}function hd(a){if(a.b)return a.b;a.a=new lc(a.url.toString(),a.c,a.f);var b=mc(a.a).then(v(a,function(a){this.a=null;return Promise.resolve(a)})),b=b.catch(v(a,function(a){this.b=this.a=null;return Promise.reject(a)}));a.b=b;return a.b}function id(a){a.a&&(a.a.ab(),a.a=null,a.b=null)};function jd(a){this.a=a}jd.prototype.destroy=function(){this.a&&(id(this.a),this.a=null)};jd.prototype.create=function(){return this.a?hd(this.a):Promise.resolve(null)};function Vc(a,b,c,d,e){this.b=a;this.a=b;this.c=c;this.f=d;this.url=e}function kd(a,b,c){return new Vc(b,c,a.c,a.f,a.url)}function dd(a,b){for(var c=a.length-1;0<=c;--c){var d=a[c];if(b>=d.b&&(null==d.a||b<d.a))return c}return-1}function ld(a,b){return a.map(function(a){return kd(a,a.b+b,null!=a.a?a.a+b:null)})};function md(){}
md.prototype.parse=function(a,b,c){var d=null;try{var e;var f=new ha(b);if(440786851!=y(f).id)e=null;else{var g=y(f);if(408125543!=g.id)e=null;else{var h=g.a.byteOffset,l;var m=new ha(g.a);for(b=null;Ma(m.a);){var t=y(m);if(357149030==t.id){b=t;break}}if(b){for(var r=new ha(b.a),m=1E6;Ma(r.a);){var A=y(r);if(2807729==A.id){m=pa(A);break}}l=m/1E9}else l=null;e=l?{Jb:h,Pb:l}:null}}if(e){var w=y(new ha(a));if(475249515!=w.id)d=null;else{var q=e.Jb,F=e.Pb;a=[];var E=new ha(w.a);for(e=w=-1;Ma(E.a);){var u=
y(E);if(187==u.id){var x;var I=new ha(u.a),wa=y(I);if(179!=wa.id)x=null;else{var He=pa(wa),Ad=y(I);if(183!=Ad.id)x=null;else{for(var Bd=new ha(Ad.a),h=0;Ma(Bd.a);){var Cd=y(Bd);if(241==Cd.id){h=pa(Cd);break}}x={Rb:He,Hb:h}}}if(x){var Dd=F*x.Rb,Ed=q+x.Hb;0<=w&&a.push(new Vc(w,Dd,e,Ed-1,c));w=Dd;e=Ed}}}0<=w&&a.push(new Vc(w,null,e,null,c));d=a}}else d=null}catch(Fd){if(!(Fd instanceof RangeError))throw Fd;}return d};function nd(){}
nd.prototype.parse=function(a,b,c){var d=null;try{a:{var e=[],f=new ia(a),g=D(f);if(1936286840!=D(f))d=null;else{1==g&&(g=Na(f));var h=oa(f);ma(f,3);ma(f,4);var l=D(f);if(0==l)d=null;else{var m,t;0==h?(m=D(f),t=D(f)):(m=Na(f),t=Na(f));ma(f,2);var r=f.b.getUint16(f.a,f.c);f.a+=2;a=m;b=b+g+t;for(g=0;g<r;g++){var A=D(f);t=(A&2147483648)>>>31;var h=A&2147483647,w=D(f);D(f);if(1==t){d=null;break a}e.push(new Vc(a/l,(a+w)/l,b,b+h-1,c));a+=w;b+=h}d=e}}}}catch(q){if(!(q instanceof RangeError))throw q;}return d};function T(a){this.s=a;this.K=0}T.prototype.destroy=function(){this.s=null};k=T.prototype;k.length=function(){return this.s.length};function U(a){if(0==a.s.length)throw new RangeError("SegmentIndex: There is no first SegmentReference.");return a.s[0]}function V(a){if(0==a.s.length)throw new RangeError("SegmentIndex: There is no last SegmentReference.");return a.s[a.s.length-1]}k.get=function(a){if(0>a||a>=this.s.length)throw new RangeError("SegmentIndex: The specified index is out of range.");return this.s[a]};
k.fa=function(a){a=dd(this.s,a);return 0<=a?this.s[a]:null};k.za=function(a){od(this,a);return!0};
function od(a,b){a.K!=b.K&&(b=new T(ld(b.s,a.K-b.K)));if(0==a.length())a.s=b.s.slice(0);else if(0!=b.length()&&null!=V(a).a&&!(null!=V(b).a&&V(b).a<V(a).a)){if(V(a).a<=U(b).b)var c=kd(V(a),V(a).b,U(b).b),c=a.s.slice(0,-1).concat([c]);else{var d;for(d=0;d<a.s.length&&!(a.s[d].a>=U(b).b);++d);a.s[d].b<U(b).b?(c=kd(a.s[d],a.s[d].b,U(b).b),c=a.s.slice(0,d).concat([c])):(U(a).b>U(b).b||U(b),c=a.s.slice(0,d))}a.s=c.concat(b.s)}}
k.ea=function(a){var b=a-this.K;if(0==b)return 0;this.s=ld(this.s,b);this.K=a;return b};k.ya=function(){return 0<this.length()?{start:U(this).b,end:V(this).a}:{start:0,end:0}};function W(a,b,c,d){T.call(this,a);this.f=b;this.u=c;this.o=d;this.c=this.i=this.a=null;pd(this)}p(W,T);W.prototype.destroy=function(){this.u=this.f=null;T.prototype.destroy.call(this)};W.prototype.fa=function(a){qd(this,ba()/1E3);return T.prototype.fa.call(this,a)};W.prototype.za=function(a){od(this,a);null==this.a&&pd(this);return!0};
function pd(a){if(0!=a.length()){a.length();var b=null!=V(a).a?V(a).a:V(a).b;if(a.f.b>a.o)a.a=b;else{var c=a.o-(a.f.b+a.u.start);0>c?a.a=b:c<Math.max(V(a).b,V(a).a||0)?(V(a),a.a=b):a.a=c}a.i=V(a).b;a.c=U(a).b}}W.prototype.ea=function(a){a=T.prototype.ea.call(this,a);null!=this.a&&(this.i+=a,this.c+=a,this.i>this.a&&(this.a+=a));return a};W.prototype.ya=function(){return rd(this,ba()/1E3)};
function rd(a,b){qd(a,b);if(null==a.a||null==a.i||null==a.c)return{start:0,end:0};var c=b-a.o,d=a.a+c;null!=a.f.f&&(d=d-a.c-a.f.f,0<d&&(a.c+=d));c=a.i+c;c=0<a.length()?null!=V(a).a?Math.min(c,V(a).a):c:a.c;c=Math.max(c,a.c);return{start:a.c,end:c}}function qd(a,b){if(null!=a.f.f)if(null==a.a)a.length();else{for(var c=a.a+(b-a.o),d=0,e=0;e<a.s.length;++e){var f=null;e<a.s.length-1?f=a.s[e+1].a:(f=a.s[e],f=null!=f.a?f.a+(f.a-f.b):null);if(null!=f&&f<c-a.f.f)++d;else break}0<d&&a.s.splice(0,d)}};function sd(a,b,c,d){var e=1,f=0,g;if(a.b>d)g=null;else{var h=a.i||0,l=a.f||0;g=c.a;g=g.a/g.b;var m=d-(a.b+b.start);0>m?g=null:(l=m-2*g-l,0>l&&(l=0),l=Math.ceil(l/g)*g,m-=g,0>m?g=null:(h=Math.floor(m/g)*g-h,0>h&&(h=0),h=Math.floor(h/g)*g,g={La:l/g+1,current:(h>=l?h:l)/g+1}))}g&&(e=g.La,f=g.current-g.La+1);e=Tc(c,e,f);if(null==e)throw a=Error("Failed to generate SegmentReferences."),a.type="stream",a;W.call(this,e,a,b,d);this.m=c;this.h=this.b=0<this.length()?a.b+b.start+V(this).a:null;this.g=g?g.current+
1:null}p(sd,W);sd.prototype.destroy=function(){this.m=null;W.prototype.destroy.call(this)};sd.prototype.fa=function(a){var b=ba()/1E3;td(this,b);qd(this,b);return T.prototype.fa.call(this,a)};sd.prototype.za=function(a){if(null!=this.b||!(a instanceof sd)||null==a.b)return!1;this.b=a.b;this.h=a.h;this.g=a.g;od(this,a);td(this,ba()/1E3);pd(this);return!0};sd.prototype.ea=function(a){a=W.prototype.ea.call(this,a);null!=this.b&&(this.b+=a,this.h+=a);return a};
sd.prototype.ya=function(){var a=ba()/1E3;td(this,a);return rd(this,a)};function td(a,b){if(null!=a.b&&null!=a.h&&null!=a.g){var c=a.m.a,c=c.a/c.b,d=Math.floor((a.h+(b-a.o)-a.b)/c);if(0!=d){var e=Tc(a.m,a.g,d);Array.prototype.push.apply(a.s,ld(e,a.K));a.b+=d*c;a.g+=d}}};function ud(a,b,c,d){this.b=a;this.f=b;this.c=c;this.g=d;this.a=null}ud.prototype.destroy=function(){this.c=this.f=this.b=null;this.a&&(this.a.destroy(),this.a=null)};
ud.prototype.create=function(){if(this.a)return Promise.resolve(this.a);for(var a=this.c.a,b=Xc(a.c),c=[],d=0;d<b.length;++d){var e=b[d].start,f=e/a.b,g=b[d].end/a.b,e=Uc(this.c,d+a.i,e);if(!e)return a=Error("Failed to generate media URL."),a.type="dash",Promise.reject(a);c.push(new Vc(f,g,0,null,new L(e)))}this.a="dynamic"==this.b.type?new W(c,this.b,this.f,this.g):new T(c);return Promise.resolve(this.a)};function vd(a,b,c,d,e,f){this.g=a;this.i=b;this.c=c;this.a=d;this.f=e;this.o=f;this.h=this.b=null}vd.prototype.destroy=function(){this.i=this.g=null;id(this.a);this.a=null;this.f&&(id(this.f),this.f=null);this.h&&(this.h.destroy(),this.h=null);this.b=null};
vd.prototype.create=function(){if(this.b)return this.b;var a=[hd(this.a)];"webm"==this.c&&a.push(hd(this.f));return this.b=Promise.all(a).then(v(this,function(a){var c=a[0];a=a[1]||null;var d=null;"mp4"==this.c?(d=new nd,d=d.parse(new DataView(c),this.a.c,this.a.url)):"webm"==this.c&&(d=new md,d=d.parse(new DataView(c),new DataView(a),this.a.url));if(!d)return c=Error("Failed to parse segment references from",this.c,"container."),c.type="stream",Promise.reject(c);c="dynamic"==this.g.type?new W(d,
this.g,this.i,this.o):new T(d);return Promise.resolve(c)}))};function wd(a,b,c,d){this.b=a;this.c=b;this.f=c;this.a=null;this.g=d}wd.prototype.destroy=function(){this.f=this.c=this.b=null;this.a&&(this.a.destroy(),this.a=null)};
wd.prototype.create=function(){if(this.a)return Promise.resolve(this.a);var a=this.f.b,b=[];a.c&&(b=Xc(a.c));var c=0;a.b&&a.h?c=a.b*a.h:0<b.length&&(c=b[0].start);var d=[],e=a.a.length;0<b.length&&b.length!=a.a.length&&(e=Math.min(b.length,a.a.length));for(var f=0;f<e;++f){var g=a.a[f],h=null,l=null,m=c/a.f;a.b?(h=c+a.b,l=h/a.f):0<b.length?(h=b[f].end,l=h/a.f):(l=m+this.c.a,h=l*a.f);var c=h,h=0,t=null;g.a&&(h=g.a.ia,t=g.a.end);d.push(new Vc(m,l,h,t,new L(g.b)))}this.a="dynamic"==this.b.type?new W(d,
this.b,this.c,this.g):new T(d);return Promise.resolve(this.a)};function xd(a,b,c,d){this.c=a;this.f=b;this.b=c;this.g=d;this.a=null}xd.prototype.destroy=function(){this.b=this.f=this.c=null;this.a&&(this.a.destroy(),this.a=null)};
xd.prototype.create=function(){if(this.a)return Promise.resolve(this.a);if("dynamic"==this.c.type)try{this.a=new sd(this.c,this.f,this.b,this.g)}catch(a){return Promise.reject(a)}else{var b=this.b.a,b=Tc(this.b,1,Math.ceil(this.f.a/(b.a/b.b)));if(!b)return b=Error("Failed to generate SegmentReferences"),b.type="stream",Promise.reject(b);this.a=new T(b)}return Promise.resolve(this.a)};function yd(a){this.b=a;this.a=null}yd.prototype.destroy=function(){this.a&&(this.a.destroy(),this.a=null)};yd.prototype.create=function(){if(this.a)return Promise.resolve(this.a);var a=new Vc(0,null,0,null,this.b);this.a=new T([a]);return Promise.resolve(this.a)};function zd(){this.C=Gd++;this.id=this.A=this.F=null;this.c=0;this.height=this.width=this.bandwidth=null;this.b=this.a="";this.enabled=!0}var Gd=0;zd.prototype.destroy=function(){this.F&&(this.F.destroy(),this.F=null);this.A&&(this.A.destroy(),this.A=null)};function Hd(a){var b=a.a||"";a.b&&(b+='; codecs="'+a.b+'"');return b}function Id(){this.C=Jd++;this.id=null;this.contentType=this.lang="";this.b=!1;this.l=[];this.a=[]}var Jd=0;
Id.prototype.destroy=function(){for(var a=0;a<this.l.length;++a)this.l[a].destroy();this.a=this.l=null};function Kd(a){for(var b=[],c=0;c<a.a.length;++c){var d=new Ld;d.id=a.C;d.a=a.a[c];d.contentType=a.contentType;d.b=a.l.length?Hd(a.l[0]):"";b.push(d)}return b}function Md(){this.id=null;this.start=0;this.b=null;this.a=[]}Md.prototype.destroy=function(){for(var a=0;a<this.a.length;++a)this.a[a].destroy();this.a=null};function Nd(){this.c=!1;this.g=this.f=null;this.b=0;this.a=[]}
Nd.prototype.destroy=function(){for(var a=0;a<this.a.length;++a)this.a[a].destroy();this.a=null};function Ld(){this.id=0;this.a=null;this.b=this.contentType=""};function gc(a,b){J.call(this,b);this.a=null;this.c=a;this.b=0}p(gc,J);
function hc(a){if(!window.indexedDB)return Promise.reject(Error("Offline storage requires IndexedDB support."));var b=new z,c=window.indexedDB.open("content_database",1);c.onupgradeneeded=v(a,function(a){this.a=a.target.result;Od(this,"group_store",{keyPath:"group_id"});Od(this,"stream_index_store",{keyPath:"stream_id"});a=Od(this,"content_store",{autoIncrement:"true"});a.createIndex("segment",["stream_id","segment_id"],{unique:!0});a.createIndex("stream","stream_id",{unique:!1})});c.onsuccess=v(a,
function(a){this.a=a.target.result;b.resolve()});c.onerror=function(){b.reject(c.error)};return b}function M(a){a.a&&a.a.close()}function Od(a,b,c){a.a.objectStoreNames.contains(b)&&a.a.deleteObjectStore(b);return a.a.createObjectStore(b,c)}
function Pd(a,b,c,d,e){for(var f=[],g=[],h=0,l=0,m=[],t=b.map(function(a){return a.F.create()}),t=Promise.all(t),r=b.map(function(a){return a.A.create()}),r=Promise.all(r),t=Promise.all([t,r]).then(function(a){f=a[0];g=a[1];h=f.reduce(function(a,b){return a+b.length()},0)}),r=0;r<b.length;++r)t=t.then(function(a){return Qd(this,b[a],f[a],g[a],h,l)}.bind(a,r)),t=t.then(function(a,b){l+=f[a].length();m.push(b)}.bind(a,r));return t.then(v(a,function(){return Rd(Sd(this))})).then(v(a,function(a){var b=
new z,f={group_id:a,stream_ids:m,session_ids:c,duration:d,key_system:e.b},g=Sd(this).put(f);g.onsuccess=function(){b.resolve(a)};g.onerror=function(){b.reject(g.error)};return b}))}function Qd(a,b,c,d,e,f){var g=[Rd(Td(a)),Rd(Ud(a).index("stream"))],g=Promise.all(g).then(v(a,function(a){return{la:Math.max(a[0],a[1]),da:new ArrayBuffer(0),Aa:0,s:[],wa:null,Qb:e,Ta:f}})),g=g.then(a.mb.bind(a,c));return g=g.then(a.nb.bind(a,b,d))}
function Rd(a){var b=new z,c=a.openCursor(null,"prev");c.onsuccess=function(a){a.target.result?b.resolve(a.target.result.key+1):b.resolve(0)};c.onerror=function(){b.reject(c.error)};return b}k=gc.prototype;k.nb=function(a,b,c){var d=new z;a={stream_id:c.la,mime_type:a.a,codecs:a.b,init_segment:b,references:c.s};var e=Td(this).put(a);e.onsuccess=function(){d.resolve(c.la)};e.onerror=function(){d.reject(e.error)};return d};
k.mb=function(a,b){for(var c=Promise.resolve(),d=0;d<a.length();++d)var e=a.get(d),f=this.ib.bind(this,e,b),c=c.then(this.Ib.bind(this,e)),c=c.then(f);return c.then(function(){return Promise.resolve(b)}).catch(v(this,function(a){Vd(this,b.la);return Promise.reject(a)}))};
k.ib=function(a,b,c){var d=new z;0==b.da.byteLength&&(b.wa=a);b.da=Wd(b.da,c);b.Ta++;var e=G({type:"progress",detail:b.Ta/b.Qb*100,bubbles:!0});if(1048576<=b.da.byteLength||null==a.a){c={stream_id:b.la,segment_id:b.Aa,content:b.da};var f=Ud(this).put(c);b.s.push({start_time:b.wa.b,start_byte:b.wa.c,end_time:a.a,url:"idb://"+b.la+"/"+b.Aa});b.Aa++;b.da=new ArrayBuffer(0);f.onerror=function(){d.reject(f.error)};f.onsuccess=v(this,function(){this.dispatchEvent(e);d.resolve()})}else this.dispatchEvent(e),
d.resolve();return d};function Wd(a,b){var c=new Uint8Array(a.byteLength+b.byteLength);c.set(new Uint8Array(a),0);c.set(new Uint8Array(b),a.byteLength);return c.buffer}k.Ib=function(a){a=new lc(a.url.toString(),a.c,a.f,void 0,void 0,this.b);a.f=this.c;return mc(a)};function ic(a,b,c){return Xd(Ud(a).index("segment"),[b,c]).then(function(a){return Promise.resolve(a.content)})}function Yd(a,b){return Xd(Td(a),b)}
function Zd(a,b){return Xd(Sd(a),b).then(v(a,function(a){return a.hasOwnProperty("duration")||a.hasOwnProperty("key_system")?Promise.resolve(a):Yd(this,a.Vb[0]).then(function(b){a.duration=b.duration;a.key_system=b.key_system;return Promise.resolve(a)})}))}function $d(a){var b=new z,c=[],d=Sd(a).openCursor();d.onerror=function(){b.reject(d.error)};d.onsuccess=function(a){(a=a.target.result)?(c.push(a.key),a.continue()):b.resolve(c)};return b}
function Xd(a,b){var c=new z,d=a.get(b);d.onerror=function(){c.reject(d.error)};d.onsuccess=function(){if(d.result)c.resolve(d.result);else{var a=Error("Item not found.");a.type="storage";c.reject(a)}};return c}
function Vd(a,b){var c=new z,d=Td(a).delete(b);d.onerror=function(){c.reject(d.error)};var e=Ud(a);e.index("stream").openKeyCursor(IDBKeyRange.only(b)).onsuccess=function(a){if(a=a.target.result)e.delete(a.primaryKey),a.continue()};e.transaction.oncomplete=function(){c.resolve()};return c}k.Ob=function(a){return Zd(this,a).then(v(this,function(b){var c=[],d;for(d in b.stream_ids)c.push(Vd(this,b.stream_ids[d]));b=Sd(this);c.push(b.delete(a));return Promise.all(c)}))};
function Ud(a){return ae(a,"content_store")}function Td(a){return ae(a,"stream_index_store")}function Sd(a){return ae(a,"group_store")}function ae(a,b){return a.a.transaction([b],"readwrite").objectStore(b)};function be(a){this.a=a}
function ce(a,b){for(var c=ba()/1E3,d=0;d<b.a.length;++d)for(var e=b.a[d],f=0;f<e.b.length;++f){var g=e.b[f];if("text"!=g.contentType)for(var h=0;h<g.a.length;++h){var l=g.a[h],m=0,m=m+(l.f?1:0),m=m+(l.b?1:0),m=m+(l.a?1:0);0==m?(g.a.splice(h,1),--h):1!=m&&(l.f?(l.b=null,l.a=null):l.b&&(l.a=null))}}de(b);for(d=0;d<b.a.length;++d)for(e=b.a[d],f=0;f<e.b.length;++f){h=g=e.b[f];l=null;for(m=0;m<h.a.length;++m){var t=h.a[m].c||"";l?t!=l&&(h.a.splice(m,1),--m):l=t}0==g.a.length&&(e.b.splice(f,1),--f)}"dynamic"==
b.type&&null==b.b&&(b.b=c);d=new Nd;"dynamic"==b.type&&(d.c=!0,d.f=b.g,d.g=b.o?new L(b.o):new L(b.url));d.b=b.h||5;for(e=0;e<b.a.length;++e){f=b.a[e];if(null==f.start)break;g=new Md;g.id=f.id;g.start=f.start||0;g.b=f.a;for(h=0;h<f.b.length;++h){l=f.b[h];m=new Id;m.id=l.id;m.c=l.c;m.lang=l.lang||"";m.contentType=l.contentType||"";m.b=l.f;for(t=0;t<l.a.length;++t){var r=l.a[t],A=m.a.slice(0),w=a,q=r,F=A,E=[];if(0==q.g.length)E.push(Mb());else if(w.a)for(var u=0;u<q.g.length;++u){var x=w.a(q.g[u]);x&&
E.push(x)}if(0==F.length)Array.prototype.push.apply(F,E);else for(w=0;w<F.length;++w){q=!1;for(u=0;u<E.length;++u)if(F[w].key()==E[u].key()){q=!0;break}q||(F.splice(w,1),--w)}if(!(0==A.length&&0<m.a.length)){w=b;E=f;F=c;if(r.j){q=null;u=1;x=0;if(r.f)q=r.c.split("/")[1],"mp4"!=q&&"webm"!=q?q=null:(u=r.f,"webm"!=q||u.c?u.a||u.b&&u.b.a?(x=u.b,x||(x=new Ac,x.url=new L(r.j),x.a=u.a?u.a.clone():null),x=ee(x),u=u.c?ee(u.c):null,F=new vd(w,E,q,x,u,F),E=new jd(u),w=new zd,w.F=F,w.A=E,q=w):q=null:q=null),u=
r.f.g,x=r.f.f;else if(r.b)q=r.b,!q.b&&!q.c&&1<q.a.length?q=null:q.b||E.a||q.c||1!=q.a.length?q.c&&0===q.c.a.length?q=null:(q=q.g?ee(q.g):null,F=new wd(w,E,r,F),E=new jd(q),w=new zd,w.F=F,w.A=E,q=w):q=null,u=r.b.f,x=r.b.i;else if(r.a){b:if(q=r.a,u=q,x=0,x+=u.f?1:0,x+=u.c?1:0,x+=u.a?1:0,0==x?u=!1:(1!=x&&(u.f?(u.c=null,u.a=null):u.c&&(u.a=null)),u=!0),u){u=null;if(q.g&&(u=(q=r.a.g)?fe(r,q,Bc):null,!u)){q=null;break b}q=u?ee(u):null;var u=r,x=q,I=u.a;if(I.f){I=void 0;I=u.c.split("/")[1];if("mp4"!=I&&
"webm"!=I)I=null;else if("webm"!=I||x)if(Uc(u,1,0)){var wa=void 0;(wa=(wa=u.a.f)?fe(u,wa,Ac):null)?(u=ee(wa),I=new vd(w,E,I,u,x,F)):I=null}else I=null;else I=null;F=I}else F=I.h?I.c?new ud(w,E,u,F):I.a?"dynamic"!=w.type&&null==E.a?null:new xd(w,E,u,F):void 0:null;F?(E=new jd(q),w=new zd,w.F=F,w.A=E,q=w):q=null}else q=null;u=r.a.b;x=r.a.o}else"text"==r.c.split("/")[0]&&(q=new zd,q.F=new yd(new L(r.j)));q?(q.id=r.id,x&&(q.c=-1*x/u),q.bandwidth=r.bandwidth,q.width=r.width,q.height=r.height,q.a=r.c||
"",q.b=r.h||"",r=q):r=null}else r=null;r&&(m.l.push(r),m.a=A)}}g.a.push(m)}d.a.push(g)}return d}
function de(a){if(a.a.length){null==a.a[0].start&&(a.a[0].start=0);var b=function(a){return 0==a||!!a};"dynamic"==a.type&&(a.c=null);b(a.c)&&1==a.a.length&&!b(a.a[0].a)&&(a.a[0].a=a.c);for(var c=0,d=!0,e=0;e<a.a.length;++e){var f=a.a[e-1],g=a.a[e],h=a.a[e+1]||{start:a.c};!b(g.start)&&f&&b(f.start)&&b(f.a)&&(g.start=f.start+f.a);!b(g.a)&&b(h.start)&&(g.a=h.start-g.start);null!=g.start&&null!=g.a?c+=g.a:d=!1}b(a.c)||(e=a.a[a.a.length-1],d?a.c=c:b(e.start)&&b(e.a)?a.c=e.start+e.a:"dynamic"!=a.type&&
(a.c=c))}}function fe(a,b,c){b=Wc(b,a.id,null,a.bandwidth,null);if(!b)return null;c=new c;c.url=a.j&&b?a.j.resolve(b):b;return c}function ee(a){var b=new L(a.url),c=0,d=null;a.a&&(c=a.a.ia,d=a.a.end);return new gd(b,c,d)};function ge(){this.streamStats=null;this.droppedFrames=this.decodedFrames=NaN;this.bufferingTime=this.playTime=this.estimatedBandwidth=0;this.playbackLatency=NaN;this.bufferingHistory=[];this.bandwidthHistory=[];this.streamHistory=[]}function he(a,b){var c=new ie(b);a.streamHistory.push(new je(c));if(c.videoHeight||!a.streamStats)a.streamStats=c}function ie(a){this.videoWidth=a.width;this.videoHeight=a.height;this.videoMimeType=a.a;this.videoBandwidth=a.bandwidth}
function je(a){this.timestamp=ba()/1E3;this.value=a};function ke(a,b,c){J.call(this,a);this.m=b;this.b=c;this.a=this.f=null;this.i=new Ha;this.h={};this.g=[];this.w=0;this.c=new z;this.u=null;this.v=0}p(ke,J);ke.prototype.destroy=function(){this.o=null;for(var a=0;a<this.g.length;++a)this.g[a].close().catch(function(){});this.g=[];this.h=this.a=this.f=null;this.i.destroy();this.m=this.b=this.i=null};
function le(a){for(var b=new B,c=a.b.Ma(),d=0;d<c.length;++d){var e=c[d];e.a.b||e.b&&!me(e.b)||b.push(e.contentType,e)}for(var d={},e=!1,f=0;f<c.length;++f){var g=c[f];if(g.a.b&&!b.a.hasOwnProperty(g.contentType)){var h=g.a.b,l=d[h];l||(l=g.a,l={audioCapabilities:void 0,videoCapabilities:void 0,initDataTypes:void 0,distinctiveIdentifier:l.i?"required":"optional",persistentState:l.m||a.b.ka()?"required":"optional"},d[h]=l);if(g.b&&(h=g.contentType+"Capabilities",h in l)){e=!0;l[h]||(l[h]=[]);var m;
"audio"==g.contentType?m=g.a.h:"video"==g.contentType&&(m=g.a.v);l[h].push({contentType:g.b,robustness:m})}}}if(!e)if(c.length)a.a=c[0].a;else throw a=Error("No DRM scheme info provided!"),a.type="drm",a;if(0==Object.keys(d).length)return a.b.Ba(b),a.c.resolve(),Promise.resolve();m=new z;d=ne(a,d,m);d=d.then(a.lb.bind(a,c,b));d=d.then(a.Kb.bind(a));m.reject(null);return d}
function oe(a,b){null==a.u&&(a.u=window.setTimeout(function(){var a=Error("Timeout waiting for sessions.");a.type="storage";this.c.reject(a)}.bind(a),b));return a.c}function ne(a,b,c){for(var d in b){var e=b[d];c=c.catch(function(){return navigator.requestMediaKeySystemAccess(d,[e])})}a.b.ka()&&(c=c.catch(function(){throw Error("Either none of the requested key systems are supported or none of the requested key systems support persistent state.");}));return c}k=ke.prototype;
k.lb=function(a,b,c){for(var d=c.keySystem,e=c.getConfiguration(),f=["audio","video"],g=0;g<f.length;++g){var h=f[g];if(!b.a.hasOwnProperty(h)){var l=e[h+"Capabilities"];if(l&&l.length){for(var l=l[0],m=[],t={},r=0;r<a.length;++r){var A=a[r];A.a.b!=d||A.b!=l.contentType||A.id in t||(m.push(A),t[A.id]=!0,this.a?Nb(this.a,A.a):this.a=A.a)}b.a[h]=m}}}this.b.Ba(b);return c.createMediaKeys()};
k.Kb=function(a){this.f=a;return this.m.setMediaKeys(this.f).then(v(this,function(){return this.a.g?this.f.setServerCertificate(this.a.g):Promise.resolve()})).then(v(this,function(){if(0<this.b.ra().length)pe(this);else{for(var a=0;a<this.a.a.length;++a){var c=this.a.a[a];this.Ra({type:"encrypted",initDataType:c.initDataType,initData:c.initData})}0==this.a.a.length&&C(this.i,this.m,"encrypted",this.Ra.bind(this))}}))};
k.Ra=function(a){var b=new Uint8Array(a.initData),c=Array.prototype.join.apply(b);if(!this.h[c]){try{var d=qe(this)}catch(e){d=H(e);this.dispatchEvent(d);this.c.reject(e);return}a=d.generateRequest(a.initDataType,a.initData);this.h[c]=!0;a.catch(v(this,function(a){if(this.h){this.h[c]=!1;var b=H(a);this.dispatchEvent(b);this.c.reject(a)}}));this.g.push(d)}};
function pe(a){for(var b=a.b.ra(),c=0;c<b.length;++c){var d=qe(a),e=d.load(b[c]);a.g.push(d);e.catch(v(a,function(a){a=H(a);this.dispatchEvent(a)}))}}function qe(a){var b=null;if(a.b.ka())try{b=a.f.createSession("persistent-license")}catch(c){throw Error("Persistent licenses are not supported by this key system or platform.");}else b=a.f.createSession();C(a.i,b,"message",a.wb.bind(a));C(a.i,b,"keystatuseschange",a.pb.bind(a));return b}k.wb=function(a){re(this,a.target,this.a,a.message)};
k.pb=function(a){a=a.target.keyStatuses.values();for(var b=a.next();!b.done;b=a.next()){var c=se[b.value];c&&(c=Error(c),c.type=b.value,b=H(c),this.dispatchEvent(b))}};
function re(a,b,c,d){d=te(c,d);oc(new nc(d.url,d.body,d.method,c.u,d.headers,a.v)).then(v(a,function(a){c.c&&(a=c.c(a));return b.update(a)})).then(v(a,function(){var a=G({type:"sessionReady",detail:b});this.dispatchEvent(a);this.w++;this.w>=this.g.length&&this.c.resolve()})).catch(v(a,function(a){a.Ub=b;a=H(a);this.dispatchEvent(a)}))}
function te(a,b){var c={url:a.o,body:b.slice(0),method:"POST",headers:{}};if(!a.f)return c;a.f(c);c.url=fa(c,"url","string");if(null==c.url)throw Error("'url' cannot be null.");if(!(c.body instanceof ArrayBuffer||"string"==typeof c.body||null==c.body))throw new TypeError("'body' must be an ArrayBuffer, a string, or null.");c.method=fa(c,"method","string");if("GET"!=c.method&&"POST"!=c.method)throw Error("'method' must be either 'GET' or 'POST'.");c.headers=ga(c,"headers",Object);if(null==c.headers)throw Error("'headers' cannot be null.");
return c}var se={"output-not-allowed":"The required output protection is not available.",expired:"A required key has expired and the content cannot be decrypted.","internal-error":"An unknown error has occurred in the CDM."};function X(a){J.call(this,null);this.a=a;this.b=null;this.f=new Ha;this.i=null;this.H="en";this.D=this.v=null;this.m=!1;this.g=new ge;this.w=!0;this.c={streamBufferSize:15,licenseRequestTimeout:0,mpdRequestTimeout:0,rangeRequestTimeout:0};this.B=1;this.u=new Lb;this.L=null}p(X,J);n("shaka.player.Player",X);X.version="1.4.0-npm-dirty";
X.isBrowserSupported=function(){return!!window.MediaSource&&!!window.MediaKeys&&!!window.navigator&&!!window.navigator.requestMediaKeySystemAccess&&!!window.MediaKeySystemAccess&&!!window.MediaKeySystemAccess.prototype.getConfiguration&&!!window.Promise&&!!Element.prototype.requestFullscreen&&!!document.exitFullscreen&&"fullscreenElement"in document&&!!window.Uint8Array};function me(a){return"text/vtt"==a?!!window.VTTCue:MediaSource.isTypeSupported(a)}X.isTypeSupported=me;
X.setTextStyle=function(a){var b=document.getElementById("ShakaPlayerTextStyle");b||(b=document.createElement("style"),b.id="ShakaPlayerTextStyle",document.head.appendChild(b));for(b=b.sheet;b.cssRules.length;)b.deleteRule(0);b.insertRule("::cue { "+Fb(a)+" }",0)};X.prototype.destroy=function(){return this.M().then(v(this,function(){this.f.destroy();this.a=this.f=null})).catch(function(){})};X.prototype.destroy=X.prototype.destroy;
X.prototype.M=function(){if(!this.b)return Promise.resolve();this.m&&ue(this);this.a.pause();Ia(this.f);ve(this);we(this);this.i.destroy();this.i=null;this.a.src="";var a=this.a.setMediaKeys(null);this.b&&(this.b.destroy(),this.b=null);this.m=!1;this.g=new ge;return a};X.prototype.unload=X.prototype.M;
X.prototype.cb=function(a){var b=this.M();this.a.autoplay&&(tb("load"),C(this.f,this.a,"timeupdate",this.ob.bind(this)));a.P(this.c);a.Za(this.L);this.L=null;a.Ca(this.w);return b.then(v(this,function(){return a.V(this.H)})).then(v(this,function(){this.b=a;this.b.ua(this.u);this.i=new ke(this,this.a,this.b);return le(this.i)})).then(v(this,function(){C(this.f,this.a,"error",this.Lb.bind(this));C(this.f,this.a,"playing",this.tb.bind(this));C(this.f,this.a,"pause",this.sb.bind(this));return this.b.Ja(this,
this.a)})).then(v(this,function(){xe(this)})).catch(v(this,function(b){a.destroy();this.b=null;this.i&&(this.i.destroy(),this.i=null);var d=H(b);this.dispatchEvent(d);return Promise.reject(b)}))};X.prototype.load=X.prototype.cb;k=X.prototype;k.ob=function(){wb("load");this.g.playbackLatency=xb("load")/1E3;this.f.na(this.a,"timeupdate")};k.Lb=function(){if(this.a.error){var a=this.a.error.code;a!=MediaError.MEDIA_ERR_ABORTED&&(a=Error(ye[a]||"Unknown playback error."),a.type="playback",a=H(a),this.dispatchEvent(a))}};
k.tb=function(){tb("playing");!this.v&&0>this.B&&(this.a.playbackRate=0,this.G(this.a.currentTime,Date.now(),this.B));this.m&&ue(this)};k.sb=function(){wb("playing");var a=xb("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3}we(this)};
k.$a=function(){if(!this.a.paused){wb("playing");var a=xb("playing");if(!isNaN(a)){var b=this.g;b.playTime+=a/1E3;tb("playing")}}a=this.g;b=this.a;b.getVideoPlaybackQuality&&(b=b.getVideoPlaybackQuality(),a.decodedFrames=b.totalVideoFrames,a.droppedFrames=b.droppedVideoFrames);return this.g};X.prototype.getStats=X.prototype.$a;X.prototype.ga=function(){return this.b?this.b.Fa():[]};X.prototype.getVideoTracks=X.prototype.ga;X.prototype.ba=function(){return this.b?this.b.Ea():[]};
X.prototype.getAudioTracks=X.prototype.ba;X.prototype.qa=function(){return this.b?this.b.Va():[]};X.prototype.getTextTracks=X.prototype.qa;X.prototype.gb=function(a,b){return this.b?this.b.Ga(a,void 0==b?!0:b):!1};X.prototype.selectVideoTrack=X.prototype.gb;X.prototype.eb=function(a,b){return this.b?this.b.Xa(a,void 0==b?!0:b):!1};X.prototype.selectAudioTrack=X.prototype.eb;X.prototype.fb=function(a){return this.b?this.b.Ya(a,!1):!1};X.prototype.selectTextTrack=X.prototype.fb;
X.prototype.T=function(a){this.b&&this.b.Da(a)};X.prototype.enableTextTrack=X.prototype.T;X.prototype.oa=function(a){this.h({enableAdaptation:a})};X.prototype.enableAdaptation=X.prototype.oa;X.prototype.P=function(){return this.w};X.prototype.getAdaptationEnabled=X.prototype.P;X.prototype.aa=function(a){this.h({streamBufferSize:a})};X.prototype.setStreamBufferSize=X.prototype.aa;X.prototype.X=function(){return Number(this.c.streamBufferSize)};X.prototype.getStreamBufferSize=X.prototype.X;
X.prototype.bb=function(a){this.h({licenseRequestTimeout:a})};X.prototype.setLicenseRequestTimeout=X.prototype.bb;X.prototype.Z=function(a){this.h({mpdRequestTimeout:a})};X.prototype.setMpdRequestTimeout=X.prototype.Z;X.prototype.jb=function(a){this.h({rangeRequestTimeout:a})};X.prototype.setRangeRequestTimeout=X.prototype.jb;X.prototype.$=function(a){this.h({preferredLanguage:a})};X.prototype.setPreferredLanguage=X.prototype.$;
X.prototype.I=function(a){we(this);0<=a?this.a.playbackRate=a:this.a.paused||(this.a.playbackRate=0,this.G(this.a.currentTime,Date.now(),a));this.B=a};X.prototype.setPlaybackRate=X.prototype.I;X.prototype.R=function(){return this.B};X.prototype.getPlaybackRate=X.prototype.R;X.prototype.kb=function(a){this.h({restrictions:a})};X.prototype.setRestrictions=X.prototype.kb;X.prototype.S=function(){return this.u.clone()};X.prototype.getRestrictions=X.prototype.S;X.prototype.hb=function(a){this.L=a};
X.prototype.setPlaybackStartTime=X.prototype.hb;X.prototype.ha=function(){return this.b?this.b.Wa():!1};X.prototype.isLive=X.prototype.ha;
X.prototype.h=function(a){if(a){var b;b=fa(a,"enableAdaptation","boolean");null!=b&&(this.w=b,this.b&&this.b.Ca(b));b=ea(a,"streamBufferSize");null!=b&&(this.c.streamBufferSize=b);b=ea(a,"licenseRequestTimeout");null!=b&&(this.c.licenseRequestTimeout=b);b=ea(a,"mpdRequestTimeout");null!=b&&(this.c.mpdRequestTimeout=b);b=ea(a,"rangeRequestTimeout");null!=b&&(this.c.rangeRequestTimeout=b);this.b&&this.b.P(this.c);b=fa(a,"preferredLanguage","string");null!=b&&(this.H=Va(b));a=ga(a,"restrictions",Lb);
null!=a&&(this.u=a.clone(),this.b&&this.b.ua(this.u))}};X.prototype.configure=X.prototype.h;X.prototype.pa=function(){return{enableAdaptation:this.w,streamBufferSize:this.c.streamBufferSize,licenseRequestTimeout:this.c.licenseRequestTimeout,mpdRequestTimeout:this.c.mpdRequestTimeout,rangeRequestTimeout:this.c.rangeRequestTimeout,preferredLanguage:this.H,restrictions:this.u.clone()}};X.prototype.getConfiguration=X.prototype.pa;function we(a){a.v&&(window.clearTimeout(a.v),a.v=null)}
function xe(a){ve(a);a.D=window.setTimeout(a.Y.bind(a),100)}function ve(a){a.D&&(window.clearTimeout(a.D),a.D=null)}X.prototype.G=function(a,b,c){var d=.1*Math.abs(c);this.a.buffered.length&&this.a.buffered.start(0)+d<this.a.currentTime?(this.a.currentTime=a+(Date.now()-b)/1E3*c,this.v=window.setTimeout(this.G.bind(this,a,b,c),100)):this.a.pause()};function ue(a){wb("buffering");var b=a.g;b.bufferingTime+=xb("buffering")/1E3;a.m=!1;a.dispatchEvent(G({type:"bufferingEnd"}))}
X.prototype.Y=function(){xe(this);if(!this.a.ended&&!this.a.seeking){var a=this.a.buffered,b=a.length?a.end(a.length-1):0,a=b-this.a.currentTime,b=b+.05;this.m?a>this.b.Na()&&(ue(this),this.a.play()):b<this.a.duration&&.1>a&&!this.a.paused&&(this.m=!0,this.a.pause(),this.g.bufferingHistory.push(ba()/1E3),tb("buffering"),this.dispatchEvent(G({type:"bufferingStart"})))}};var ye={2:"A network failure occured while loading media content.",3:"The browser failed to decode the media content.",4:"The browser does not support the media content."};function ze(a,b,c){J.call(this,null);this.f=a;this.c=b;this.b=c?c:Mb();this.a=null}p(ze,J);n("shaka.player.HttpVideoSource",ze);ze.prototype.P=function(){};ze.prototype.destroy=function(){this.a&&(this.a.parentElement.removeChild(this.a),this.a=null);this.o=this.b=null};k=ze.prototype;k.Ja=function(a,b){this.o=a;var c=b.mediaKeys;b.src=this.f;c=b.setMediaKeys(c);this.c&&(this.a=document.createElement("track"),this.a.src=this.c,b.appendChild(this.a),this.a.track.mode="showing");return c};k.V=function(){return Promise.resolve()};
k.Fa=function(){return[]};k.Ea=function(){return[]};k.Va=function(){return[]};k.Na=function(){return 5};k.Ma=function(){var a=new Ld;a.a=this.b;return[a]};k.Ba=function(){};k.Ga=function(){return!1};k.Xa=function(){return!1};k.Ya=function(){return!1};k.Da=function(a){this.a&&(this.a.track.mode=a?"showing":"disabled")};k.Za=function(){};k.Ca=function(){};k.ua=function(){};k.ra=function(){return[]};k.ka=function(){return!1};k.Wa=function(){return!1};function Ae(a){this.b=a;this.a=null}Ae.prototype.destroy=function(){this.b=null;this.a&&(this.a.destroy(),this.a=null)};Ae.prototype.create=function(){if(this.a)return Promise.resolve(this.a);for(var a=[],b=0;b<this.b.length;++b){var c=this.b[b];a.push(new Vc(c.start_time,c.end_time,c.start_byte,null,new L(c.url)))}this.b=null;this.a=new T(a);return Promise.resolve(this.a)};function Be(a,b,c,d,e){J.call(this,a);this.f=b;this.a=new Yc(c,d,e);this.v=this.D=this.b=null;this.H=0;this.G=!1;this.i=null;this.g=!1;this.c=null;this.m=this.h=!1;this.u=15;this.w=!1}p(Be,J);Be.prototype.B=function(a){null!=a.streamBufferSize&&(this.u=Number(a.streamBufferSize));null!=a.rangeRequestTimeout&&(this.a.m=Number(a.rangeRequestTimeout))};Be.prototype.destroy=function(){Ce(this);this.b=null;this.a.destroy();this.o=this.f=this.a=null};k=Be.prototype;k.ja=function(){return this.b};k.Oa=function(){return this.D};
k.Qa=function(){return this.h};k.Pa=function(){return this.m};k.ma=function(a,b,c){if(a!=this.b){var d=[a.F.create(),a.A.create()];Promise.all(d).then(v(this,function(d){var f=this.b;this.b=a;this.D=d[0];this.v=d[1];this.H=b;this.G=!0;this.g||(f?c&&De(this,!0):Ee(this,0))})).catch(v(this,function(a){"aborted"!=a.type&&(a=H(a),this.dispatchEvent(a))}))}};k.Ua=function(){return De(this,!1)};
function De(a,b){a.b&&!a.g&&(a.g=!0,Ce(a),$c(a.a).then(v(a,function(){var a=this.f.currentTime;if(!b&&0<ad(this.a,a)&&0<=dd(this.a.b,a))return Promise.resolve();this.w=!0;return fd(this.a)})).then(v(a,function(){this.g=!1;Ee(this,0)})).catch(v(a,function(a){this.g=!1;a=H(a);this.dispatchEvent(a)})))}k.ta=function(){};k.xa=function(){return!0};
k.Cb=function(){var a;a=1<this.a.c.buffered.length?!0:!1;if(a&&this.h)De(this,!0);else{this.i=null;a=this.b;var b=this.D,c=this.f.currentTime,d=ad(this.a,c),e=this.h?this.u:Math.min(this.H,this.u)+(this.c||0);d>=e?(Fe(this),Ee(this,1E3/(Math.abs(this.f.playbackRate)||1))):(b=Ge(this,c,b))?(b=bd(this.a,b,this.v),this.v=null,this.G&&(this.G=!1,Ie(this,a)),b.then(v(this,function(a){this.m=!1;null==this.c&&(this.c=a);this.w&&0<ad(this.a,c)&&(this.w=!1,this.f.currentTime+=.001);Ee(this,0)})).catch(v(this,
function(a){if("aborted"!=a.type){var b=H(a);this.dispatchEvent(b);b=[0,404,410];"net"==a.type&&-1!=b.indexOf(a.Sb.status)&&Ee(this,5E3)}}))):(Fe(this),this.m||(this.m=!0,Je(this)),Ee(this,1E3))}};function Ge(a,b,c){a=a.a;var d=a.b.length;a=0<d?a.b[d-1]:null;return null!=a?null!=a.a?c.fa(a.a):null:c.fa(b)}function Fe(a){if(!a.h&&null!=a.c){a.h=!0;var b=a.a,c=a.c,d=c-b.u;0!=d&&(b.b=ld(b.b,d),b.u=c);b=G({type:"started",bubbles:!1,K:a.c});a.dispatchEvent(b)}}
function Ie(a,b){var c=b.a.split("/")[0],c=G({type:"adaptation",bubbles:!0,contentType:c,size:"video"!=c?null:{width:b.width,height:b.height},bandwidth:b.bandwidth});a.dispatchEvent(c)}function Je(a){var b=G({type:"ended"});a.dispatchEvent(b)}function Ee(a,b){a.i=window.setTimeout(a.Cb.bind(a),b)}function Ce(a){null!=a.i&&(window.clearTimeout(a.i),a.i=null)};function Ke(a){for(var b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.a.length;++d){for(var e=c.a[d],f=e,g=0;g<f.l.length;++g)me(Hd(f.l[g]))||(f.l.splice(g,1),--g);0==e.l.length&&(c.a.splice(d,1),--d)}}function Le(a){for(var b=0;b<a.length;++b)for(var c=a[b],d=0;d<c.a.length;++d)c.a[d].l.sort(Me)}function Me(a,b){var c=a.bandwidth||Number.MAX_VALUE,d=b.bandwidth||Number.MAX_VALUE;return c<d?-1:c>d?1:0};function Ne(a){this.a=a}Ne.prototype.destroy=function(){this.a.destroy();this.a=null};function Oe(a,b){var c=Pe(b),d=Pe(a.a);return Promise.all([c,d]).then(v(a,function(a){var c=a[0];a=a[1];var d=this.a.a;Ke(d);Le(d);b.f=this.a.f;b.g=this.a.g?new L(this.a.g):null;b.b=this.a.b;d=[];Qe(b,this.a,c,a,d);c=b.a;Ke(c);Le(c);return Promise.resolve(d)}))}
function Pe(a){function b(a,b){return a.concat(b)}var c=a.a.map(function(a){return a.a}).reduce(b,[]).map(function(a){return a.l}).reduce(b,[]);a=c.map(function(a){return a.F.create()});return Promise.all(a).then(function(a){for(var b={},f=0;f<c.length;++f)b[c[f].C]=a[f];return Promise.resolve(b)})}
function Qe(a,b,c,d,e){var f=new B;a.a.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new B;b.a.forEach(function(a,b){g.push(a.id||""+b,a)});a=za(f);for(b=0;b<a.length;++b){var h=a[b],l=f.get(h);1<l.length||(h=g.get(h))&&0!=h.length&&1==h.length&&(Re(l[0],h[0],c,d,e),l[0].b=h[0].b)}}
function Re(a,b,c,d,e){var f=new B;a.a.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new B;b.a.forEach(function(a,b){g.push(a.id||""+b,a)});a=za(f);for(b=0;b<a.length;++b){var h=a[b],l=f.get(h);1<l.length||(h=g.get(h))&&0!=h.length&&1==h.length&&Se(l[0],h[0],c,d,e)}}
function Se(a,b,c,d,e){var f=new B;a.l.forEach(function(a,b){f.push(a.id||""+b,a)});var g=new B;b.l.forEach(function(a,b){g.push(a.id||""+b,a)});b={};for(var h=za(f),l=0;l<h.length;++l){var m=h[l];b[m]=m;var t=f.get(m);1<t.length||((m=g.get(m))&&0!=m.length?1==m.length&&(Te(t[0],m[0],c,d),t[0].A=m[0].A,m[0].A=null,t[0].c=m[0].c):(e.push(t[0]),a.l.splice(a.l.indexOf(t[0]),1)))}h=za(g);for(l=0;l<h.length;++l)m=h[l],b[m]||(b[m]=m,m=g.get(m),a.l.push(m[0]))}
function Te(a,b,c,d){a=c[a.C];b=d[b.C];a.length();a.za(b)&&a.length()};function Ue(a,b){J.call(this,a);this.b=b;this.g=!0;this.a=this.c=this.f=null}p(Ue,J);Ue.prototype.B=function(){};Ue.prototype.destroy=function(){this.a&&this.b.removeChild(this.a);this.o=this.b=this.f=this.c=this.a=null};k=Ue.prototype;k.ja=function(){return this.f};k.Oa=function(){return this.c};k.Qa=function(){return!0};k.Pa=function(){return!0};
k.ma=function(a){a.F.create().then(v(this,function(b){if(this.b){this.f=a;this.c=b;if(0==b.length())return Promise.reject(Error("No subtitles URL available."));b=U(b).url.toString();var c=this.xa();this.a&&(this.ta(!1),this.b.removeChild(this.a));this.a=document.createElement("track");this.b.appendChild(this.a);this.a.src=b;this.ta(c)}}))};k.Ua=function(){};k.ta=function(a){this.g=a;this.a&&(this.a.track.mode=a?"showing":"disabled")};k.xa=function(){return this.g};function Ve(){this.a=this.c=null;this.f=new Ha;this.b=Number.POSITIVE_INFINITY;this.g=!0}n("shaka.media.SimpleAbrManager",Ve);Ve.prototype.destroy=function(){this.f.destroy();this.a=this.c=this.f=null};Ve.prototype.start=function(a,b){this.c&&this.a||(this.c=a,this.a=b,this.b=Date.now()+4E3,C(this.f,this.c,"bandwidth",this.i.bind(this)),C(this.f,this.a,"adaptation",this.h.bind(this)))};Ve.prototype.enable=function(a){this.g=a};
Ve.prototype.getInitialVideoTrackId=function(){if(!this.a||!this.c)return null;var a=We(this);return a?a.id:null};Ve.prototype.i=function(){if(this.g&&!(Date.now()<this.b)){var a=We(this);if(a){if(a.active){this.b=Date.now()+3E3;return}this.a.Ga(a.id,!1)}this.b=Number.POSITIVE_INFINITY}};Ve.prototype.h=function(){this.b==Number.POSITIVE_INFINITY&&(this.b=Date.now()+3E4)};
function We(a){var b=a.a.Fa();if(0==b.length)return null;b.sort(zb);var c;a:{c=a.a.Ea();for(var d=0;d<c.length;++d)if(c[d].active){c=c[d];break a}c=null}c=c?c.bandwidth:0;a=a.c.getBandwidth();for(var d=b[0],e=0;e<b.length;++e){var f=b[e],g=e+1<b.length?b[e+1]:{bandwidth:Number.POSITIVE_INFINITY};if(f.bandwidth&&(g=(g.bandwidth+c)/.85,a>=(f.bandwidth+c)/.95&&a<=g&&(d=f,d.active)))break}return d};function Y(a,b,c){J.call(this,null);this.a=a;this.B=b;this.i=new Ha;this.g=new MediaSource;this.f=null;this.Z=0;this.c=new B;this.H=c;this.v=!1;this.D="";this.aa=!1;this.G=null;this.X=new z;this.u=this.Y=null;this.qa=1;this.b={};this.pa=Number.POSITIVE_INFINITY;this.w=Number.NEGATIVE_INFINITY;this.L=0;this.oa=!1;this.m={};this.R=this.M=this.S=null;this.$={}}p(Y,J);n("shaka.player.StreamVideoSource",Y);
Y.prototype.P=function(a){null!=a.streamBufferSize&&(this.$.streamBufferSize=a.streamBufferSize);null!=a.rangeRequestTimeout&&(this.$.rangeRequestTimeout=a.rangeRequestTimeout);for(var b in this.b)this.b[b].B(this.$);null!=a.mpdRequestTimeout&&(this.Z=Number(a.mpdRequestTimeout))};
Y.prototype.destroy=function(){this.M&&(window.clearTimeout(this.M),this.M=null);this.S&&(window.clearTimeout(this.S),this.S=null);this.m=null;this.i.destroy();this.i=null;da(this.b).forEach(function(a){a.destroy()});this.c=this.b=null;this.a&&(this.a.destroy(),this.a=null);this.H.destroy();this.o=this.Y=this.X=this.G=this.f=this.g=this.B=this.H=null};k=Y.prototype;
k.Ja=function(a,b){if(!this.v){var c=Error("Cannot call attach() right now.");c.type="stream";return Promise.reject(c)}this.o=a;this.f=b;this.G=a.$a();C(this.i,this.g,"sourceopen",this.rb.bind(this));C(this.i,this.B,"bandwidth",this.Mb.bind(this));c=this.f.mediaKeys;this.f.src=window.URL.createObjectURL(this.g);c=this.f.setMediaKeys(c);return Promise.all([this.X,c])};
k.V=function(a){if(this.v)return a=Error("Cannot call load() right now."),a.type="stream",Promise.reject(a);if(!this.a||0==this.a.a.length)return a=Error("The manifest does not specify any content."),a.type="stream",Promise.reject(a);this.D=a;a=this.a.a;Ke(a);Le(a);if(0==this.a.a.length||0==this.a.a[0].a.length)return a=Error("The manifest specifies content that cannot be displayed on this browser/platform."),a.type="stream",Promise.reject(a);this.v=!0;return Promise.resolve()};
k.Ab=function(){var a=Date.now(),b=this.S=null;this.Sa(this.a.g).then(v(this,function(a){b=new Ne(a);return Oe(b,this.a)})).then(v(this,function(c){b.destroy();b=null;for(var d=0;d<c.length;++d)Xe(this,c[d]);this.Y&&this.ua(this.Y);0==Object.keys(this.b).length?Ye(this):Ze(this,(Date.now()-a)/1E3)})).catch(v(this,function(a){b&&(b.destroy(),b=null);"aborted"!=a.type&&(a=H(a),this.dispatchEvent(a),this.a&&Ze(this,0))}))};k.Sa=function(){return Promise.reject("Cannot update manifest with this VideoSource implementation.")};
function Xe(a,b){var c=b.a.split("/")[0],d=a.b[c];if(d&&d.ja()==b){var e=a.c.get(b.a.split("/")[0]),f=e.map(function(a){return a.l}).reduce(function(a,b){return a.concat(b)},[]).filter(function(a){return a.enabled});if(0==f.length){e.push(b);return}a.m[c].Ha==b&&delete a.m[c];d.ma(f[0],a.a.b,!0);b.destroy()}b.destroy()}
k.Fa=function(){if(!this.c.a.hasOwnProperty("video"))return[];for(var a=this.b.video,a=(a=a?a.ja():null)?a.C:0,b=[],c=this.c.get("video"),d=0;d<c.length;++d)for(var e=c[d],f=0;f<e.l.length;++f){var g=e.l[f];if(g.enabled){var h=g.C,g=new yb(h,g.bandwidth,g.width,g.height);h==a&&(g.active=!0);b.push(g)}}return b};
k.Ea=function(){if(!this.c.a.hasOwnProperty("audio"))return[];for(var a=this.b.audio,a=(a=a?a.ja():null)?a.C:0,b=[],c=this.c.get("audio"),d=0;d<c.length;++d)for(var e=c[d],f=e.lang,g=0;g<e.l.length;++g){var h=e.l[g],l=h.C,h=new Hb(l,h.bandwidth,f);l==a&&(h.active=!0);b.push(h)}return b};
k.Va=function(){if(!this.c.a.hasOwnProperty("text"))return[];for(var a=this.b.text,b=a?a.ja():null,b=b?b.C:0,c=[],d=this.c.get("text"),e=0;e<d.length;++e)for(var f=d[e],g=f.lang,h=0;h<f.l.length;++h){var l=f.l[h].C,m=new Ab(l,g);l==b&&(m.active=!0,m.enabled=a.xa());c.push(m)}return c};k.Na=function(){return this.a&&this.a.b||0};k.Ma=function(){var a;if(this.v){a=this.a.a[0];for(var b=[],c=0;c<a.a.length;++c)b.push.apply(b,Kd(a.a[c]));a=b}else a=[];return a};
k.Ba=function(a){if(this.v){for(var b={},c=this.a.a[0],d=0;d<c.a.length;++d){var e=c.a[d];b[e.C]=e}this.c.a={};c=za(a);for(d=0;d<c.length;++d){var e=c[d],f=a.get(e);if("video"==e){var g=f[0].id;this.c.push(e,b[g])}else if("audio"==e)for(var g=f[0].b.split(";")[0],h=0;h<f.length;++h){var l=f[h];l.b.split(";")[0]==g&&this.c.push(e,b[l.id])}else for(h=0;h<f.length;++h)g=f[h].id,this.c.push(e,b[g])}this.aa=!0;if(a=this.c.get("audio"))$e(this,a),this.c.a.audio=a,a=a[0].lang||this.D,Ua(2,this.D,a)&&(this.aa=
!1);if(a=this.c.get("text"))$e(this,a),this.c.a.text=a,a=a[0].lang||this.D,Ua(2,this.D,a)||(this.aa=!1)}};k.Ga=function(a,b){return af(this,"video",a,b)};k.Xa=function(a,b){return af(this,"audio",a,b)};k.Ya=function(a,b){return af(this,"text",a,b)};k.Da=function(a){var b=this.b.text;b&&b.ta(a)};k.Za=function(a){this.R=a};k.Ca=function(a){this.H.enable(a)};
k.ua=function(a){if(this.v){this.Y=a;for(var b=0;b<this.a.a.length;++b)for(var c=this.a.a[b],d=0;d<c.a.length;++d)for(var e=c.a[d],f=0;f<e.l.length;++f){var g=e.l[f];g.enabled=!0;a.maxWidth&&g.width>a.maxWidth&&(g.enabled=!1);a.maxHeight&&g.height>a.maxHeight&&(g.enabled=!1);a.maxBandwidth&&g.bandwidth>a.maxBandwidth&&(g.enabled=!1);a.minBandwidth&&g.bandwidth<a.minBandwidth&&(g.enabled=!1)}}};k.ra=function(){return[]};k.ka=function(){return!1};k.Wa=function(){return this.a?this.a.c:!1};
function af(a,b,c,d){if(!a.c.a.hasOwnProperty(b)||!a.b[b])return!1;for(var e=a.c.get(b),f=0;f<e.length;++f)for(var g=e[f],h=0;h<g.l.length;++h){var l=g.l[h];if(l.C==c){if("text"!=b&&!a.oa)return c=a.m[b],a.m[b]={Ha:l,Ka:null!=c&&c.Ka||d},!0;he(a.G,l);a.b[b].ma(l,a.a.b,d);return!0}}return!1}
function $e(a,b){for(var c=0;2>=c;++c)for(var d=0;d<b.length;++d){var e=b[d];if(Ua(c,a.D,e.lang)){b.splice(d,1);b.splice(0,0,e);return}}for(d=0;d<b.length;++d)if(e=b[d],e.b){b.splice(d,1);b.splice(0,0,e);break}}k.rb=function(){this.i.na(this.g,"sourceopen");Ye(this).then(v(this,function(){this.X.resolve()})).catch(v(this,function(a){this.X.reject(a)}))};
function Ye(a){for(var b=[],c=["audio","video","text"],d=0;d<c.length;++d){var e=c[d];a.c.a.hasOwnProperty(e)&&b.push(a.c.get(e)[0])}a.H.start(a.B,a);var f=bf(a,b),b=da(f).map(function(a){return a.F.create()});return Promise.all(b).then(v(a,function(a){if(!a.every(function(a){return a.length()}))return a=Error("Some streams are not available."),a.type="stream",Promise.reject(a);a=cf(this,a);if(!a)return a=Error("Some streams are not available."),a.type="stream",Promise.reject(a);if(!df(this,f))return a=
Error("Failed to create Stream objects."),a.type="stream",Promise.reject(a);ef(this,f,a);return Promise.resolve()})).catch(v(a,function(a){if("aborted"!=a.type)return Object.keys(this.b),this.a.c?(Ze(this,0),Promise.resolve()):Promise.reject(a)}))}
function bf(a,b){for(var c={},d=0;d<b.length;++d){var e=b[d],f=e.l[0];if("video"==e.contentType)for(var g=a.H.getInitialVideoTrackId(),h=0;h<e.l.length&&(f=e.l[h],f.C!=g);++h);else"audio"==e.contentType&&(f=e.l[Math.floor(e.l.length/2)]);c[e.contentType]=f}return c}function df(a,b){var c={},d;for(d in b){var e=b[d],e="text"==d?new Ue(a,a.f):ff(a,e);if(!e)return da(c).forEach(function(a){a.destroy()}),!1;c[d]=e}a.b=c;return!0}
function ff(a,b){var c;try{c=a.g.addSourceBuffer(Hd(b))}catch(d){return null}try{c.timestampOffset=b.c}catch(e){return null}c=new Be(a,a.f,a.g,c,a.B);c.B(a.$);return c}
function ef(a,b,c){a.qa=a.f.playbackRate;a.f.playbackRate=0;var d;a.a.c?(a.g.duration=c.end+2592E3,d=c.end):(a.g.duration=c.end-c.start,d=a.R&&a.R<=c.end&&a.R>=c.start?a.R:c.start);C(a.i,a.f,"seeking",a.vb.bind(a));a.f.currentTime!=d&&(a.f.currentTime=d,a.u=d);gf(a,c.start,c.end);for(var e in a.b)c=a.b[e],C(a.i,c,"started",a.yb.bind(a)),C(a.i,c,"ended",a.xb.bind(a)),d=b[e],he(a.G,d),c.ma(d,a.a.b,!1);a.Da(a.aa)}
k.yb=function(a){this.pa=Math.min(this.pa,a.K);this.w=Math.max(this.w,a.K);for(var b in this.b)if(!this.b[b].Qa())return;hf(this)};
function hf(a){for(var b=jf(a),c=0;c<b.length;++c)b[c].ea(a.w);kf(a,b);b=xa(a.c).map(function(a){return a.l}).reduce(function(a,b){return a.concat(b)},[]).map(function(a){var b=[a.F.create()];a.A&&b.push(a.A.create());return Promise.all(b)});Promise.all(b).then(v(a,function(a){for(var b=0;b<a.length;++b)a[b][0].ea(this.w);this.oa=!0;for(var c in this.m)a=this.m[c],b=this.b[c],he(this.G,a.Ha),b.ma(a.Ha,this.a.b,a.Ka);this.m={}})).catch(v(a,function(a){"aborted"!=a.type&&(a=H(a),this.dispatchEvent(a))}))}
function kf(a,b){var c=cf(a,b);c&&gf(a,c.start,c.end);var d;0!=a.w?(d=a.f.currentTime+a.w,a.f.currentTime=d,a.u=d):d=a.f.currentTime;a.a.c&&c&&(a.L=c.end-d,a.L=Math.max(a.L,0));a.f.playbackRate=a.qa;null!=a.a.f&&Ze(a,a.L);lf(a)}k.Bb=function(){this.M=null;lf(this);var a=cf(this,jf(this));a&&(gf(this,a.start,a.end),this.f.paused||mf(this,this.f.currentTime,a.start,a.end))};function gf(a,b,c){b=G({type:"seekrangechanged",bubbles:!0,start:b,end:c});a.dispatchEvent(b)}
k.vb=function(){var a=this.f.currentTime;if(null!=this.u){if(a>=this.u-.01&&a<=this.u+.01){this.u=null;return}this.u=null}var b=cf(this,jf(this));if(b){var c=b.end;(b=mf(this,a,b.start,c))||(a<=c+.01?b=!1:(this.f.currentTime=c,b=!0));if(!b)for(var d in this.b)this.b[d].Ua()}};function mf(a,b,c,d){if(b>=c-.01)return!1;a.f.currentTime=Math.min(c+(a.a.c?a.a.b:0),d);return!0}k.xb=function(){if(!this.a.c){for(var a in this.b)if(!this.b[a].Pa())return;"open"==this.g.readyState&&this.g.endOfStream()}};
k.Mb=function(){var a=this.G,b=this.B.getBandwidth();a.estimatedBandwidth=b;a.bandwidthHistory.push(new je(b))};function jf(a){return da(a.b).map(function(a){return a.Oa()}).filter(function(a){return null!=a})}
function cf(a,b){for(var c=0,d=Number.POSITIVE_INFINITY,e=0;e<b.length;++e){var f=b[e].ya(),c=Math.max(c,f.start);null!=f.end&&(d=Math.min(d,f.end))}if(d==Number.POSITIVE_INFINITY)if(d=a.a.a[0],d.b)d=(d.start||0)+d.b;else return null;a.a.c&&(d=Math.max(d-(a.a.b+a.L),c));return c>d?null:{start:c,end:d}}function Ze(a,b){if(null!=a.a.f){var c=Math.max(a.a.f,3),c=Math.max(c-b,0);a.S=window.setTimeout(a.Ab.bind(a),1E3*c)}}function lf(a){a.a.c&&(a.M=window.setTimeout(a.Bb.bind(a),1E3))};function Z(a,b,c){b||(b=new bb);c||(c=new Ve);Y.call(this,null,b,c);this.T=a;this.I=[];this.timeoutMs=3E4;this.h={}}p(Z,Y);n("shaka.player.OfflineVideoSource",Z);Z.prototype.P=function(a){null!=a.licenseRequestTimeout&&(this.h.licenseRequestTimeout=a.licenseRequestTimeout);null!=a.rangeRequestTimeout&&(this.h.rangeRequestTimeout=a.rangeRequestTimeout);Y.prototype.P.call(this,a)};
Z.retrieveGroupIds=function(){var a=new gc(null,null),b=hc(a).then(function(){return $d(a)});b.then(function(){M(a)}).catch(function(){M(a)});return b};
Z.prototype.ha=function(a,b,c,d){var e,f={},g=[];a=new Rc(a,this.Z);var h=Va(b);return Sc(a).then(v(this,function(a){this.a=ce(new be(c),a);return this.a.c?Promise.reject(Error("Unable to store live streams offline.")):Y.prototype.V.call(this,h)})).then(v(this,function(){var a=document.createElement("video");a.src=window.URL.createObjectURL(this.g);e=new ke(null,a,this);null!=this.h.licenseRequestTimeout&&(e.v=Number(this.h.licenseRequestTimeout));C(this.i,e,"sessionReady",this.ba.bind(this));return le(e)})).then(v(this,
function(){for(var a=xa(this.c),b=0;b<a.length;++b)for(var c=a[b],e=0;e<c.l.length;++e){var g=c.l[e];f[g.C]=g}return d()})).then(v(this,function(a){for(var b=0;b<a.length;++b){var c=a[b],d=f[c];if(d)g.push(d);else return Promise.reject(Error("Invalid stream ID chosen: "+c))}var e=["audio","video"];g=g.filter(function(a){return 0>e.indexOf(a.a.split("/")[0])?!1:!0});a=g.map(function(a){return a.A.create()});return Promise.all(a)})).then(v(this,function(a){for(var b=g,c=[],d=0;d<b.length;++d)try{c[d]=
this.g.addSourceBuffer(Hd(b[d]))}catch(e){}if(b.length!=c.length)a=Error("Error initializing streams."),a.type="storage",a=Promise.reject(a);else{for(d=0;d<a.length;++d)(b=a[d])&&c[d].appendBuffer(b);a=Promise.resolve()}return a})).then(v(this,function(){return oe(e,this.timeoutMs)})).then(v(this,function(){return nf(this,g,e.a,this.a.a[0].b)}))};Z.prototype.store=Z.prototype.ha;Z.prototype.ba=function(a){this.I.push(a.detail.sessionId)};
function nf(a,b,c,d){var e=new gc(a.B,a);null!=a.h.rangeRequestTimeout&&(e.b=Number(a.h.rangeRequestTimeout));var f=hc(e);return f=f.then(v(a,function(){return Pd(e,b,this.I,d,c)})).then(function(a){M(e);return Promise.resolve(a)}).catch(function(a){M(e);return Promise.reject(a)})}
Z.prototype.V=function(a){var b=new gc(null,null);null!=this.h.rangeRequestTimeout&&(b.b=Number(this.h.rangeRequestTimeout));var c,d;return hc(b).then(v(this,function(){return Zd(b,this.T)})).then(v(this,function(a){var f=[];this.I=a.session_ids;c=a.duration;d=a.key_system;for(var g=0;g<a.stream_ids.length;++g)f.push(Yd(b,a.stream_ids[g]));return Promise.all(f)})).then(v(this,function(b){var f=c,g=d,h=new Nd;h.b=5;for(var l=new Md,m=0;m<b.length;++m){var t=b[m],r=new zd,A=new Ae(t.references),w=new Uint8Array(t.init_segment),
w=new L("data:application/octet-stream;base64,"+ta(w)),w=new jd(new gd(w,0,null));r.F=A;r.A=w;r.a=t.mime_type;r.b=t.codecs;t=new Ib(g,"",!1,null);A=new Id;A.l.push(r);A.a.push(t);A.contentType=r.a.split("/")[0];l.a.push(A);l.b=f}h.a.push(l);this.a=h;return Y.prototype.V.call(this,a)})).then(function(){M(b);return Promise.resolve()}).catch(function(a){M(b);return Promise.reject(a)})};
Z.prototype.ga=function(){var a=new gc(null,null);null!=this.h.rangeRequestTimeout&&(a.b=Number(this.h.rangeRequestTimeout));return hc(a).then(a.Ob.bind(a,this.T)).then(function(){M(a);return Promise.resolve()}).catch(function(b){M(a);return Promise.reject(b)})};Z.prototype.deleteGroup=Z.prototype.ga;Z.prototype.ra=function(){return this.I};Z.prototype.ka=function(){return!0};function of(a,b,c,d){c||(c=new bb);d||(d=new Ve);Y.call(this,null,c,d);this.ga=a;this.I=b;this.h=[];this.T=[];this.ba=[]}p(of,Y);n("shaka.player.DashVideoSource",of);of.prototype.ha=function(a,b,c){this.h.push(a);this.T.push(b||"");this.ba.push(c||"")};of.prototype.addExternalCaptions=of.prototype.ha;of.prototype.destroy=function(){this.I=null;Y.prototype.destroy.call(this)};
of.prototype.V=function(a){return Sc(new Rc(this.ga,this.Z)).then(v(this,function(b){for(var c=0;c<this.h.length;c++){var d=b,e=this.h[c],f=this.T[c],g=this.ba[c];if(0!==d.a.length){var h=new rc;h.contentType="text";h.lang=f||"en";h.f=!0;f=new uc;f.bandwidth=0;f.c=g||"text/vtt";f.j=new L(e);h.a.push(f);d.a[0].b.push(h);Mc(d.a[0])}}this.a=ce(new be(this.I),b);return Y.prototype.V.call(this,a)}))};
of.prototype.Sa=function(a){return Sc(new Rc(a.toString(),this.Z)).then(v(this,function(a){a=ce(new be(this.I),a);return Promise.resolve(a)}))};}.bind(g,this))();
if (typeof(module)!="undefined"&&module.exports)module.exports=g.shaka;
else if (typeof(define)!="undefined")define(function(){return g.shaka});
else this.shaka=g.shaka;
})();

